### ISSUE TITLE
Proposal: allow `erased` to be used in place of a definition

### ISSUE THREAD

**Issue by japgolly** [scala/scala3#11736]
Instead of:

```scala
erased given CanThrow[Ex1] = ???
```

which is confusing to newbies and requires even experienced users to take a deep breath, what do you think about allowing the `erased` keyword itself to stand in as a fake definition? It would look like this:

```scala
erased given CanThrow[Ex1] = erased
```

**Comment by japgolly** [comment]
If the above is acceptable, then a potential next step could be to have to compiler apply the `erased` flag to any definition with `erased` as the body, 

```scala
given CanThrow[Ex1] = erased
```

**Comment by nicolasstucki** [comment]
We already have this feature.

It is exposed as the method `scala.compiletime.erasedValue`.
```scala
erased given CanThrow[Ex1] = erasedValue
```

**Comment by abgruszecki** [comment]
@nicolasstucki I guess this issue can be closed then, no?

**Comment by japgolly** [comment]
Linking to #11739
