### ISSUE TITLE
No indentation error on misaligned definitions

### ISSUE THREAD

**Issue by propensive** [scala/scala3#12183]
## Compiler version

3.0.0-RC2

## Minimized code

```Scala
object Foo:
  private
    def x = 1
    def y = 2

Foo.y
```

## Output

```scala
2 // no access error
```

`Foo.y` is not private.

## Expectation

Either the `private` modifier should apply to both the definition of `x` and `y` (which would be consistent with how `extension` is used), and `y` should be inaccessible outside of `Foo`, or an error should be emitted about the indentation level of `def y`, which ought to be aligned with `private`.

**Comment by odersky** [comment]
That's not how things are defined right now. We are intentionally loose with indentation rules, in that we do allow you to veer off the right. Enforcing strict alignment everywhere would break too much legacy code, and we do not want a mode switch. We want to freely mix indented code with legacy code. Therefore, this would under future improvements/tightenings.

**Comment by propensive** [comment]
That's fine. I tried it because I wondered whether it was possible, and the more drastic change certainly wouldn't make sense _in general_ (e.g. for `lazy`). But I'd be happy to see the (gradual, if necessary) introduction of more constraints on indentation that would ultimately make code like that in the example incorrect.

**Comment by som-snytt** [comment]
My vote is for `-language:propensive` with indent syntax for modifiers.

**Comment by sirinath** [comment]
I think the private modifier should apply to both the definition of `x` and `y`.
