### ISSUE TITLE
Empty `DefDef: Unit` with end marker 

### ISSUE THREAD

**Issue by dos65** [scala/scala3#12918]
## 3.0.0-RC2

Should the compiler allow the following empty `def`?
Currently, it fails with an error from the parser.

```scala
 def foo: Unit = //<- [error] expression expected but end found
 end foo 
```

**Comment by som-snytt** [comment]
Related use case at https://github.com/lampepfl/dotty/issues/12185#issuecomment-824890648 which was about (transiently) empty class template during development. (Where empty template body after colon is allowed with end marker.)

What if the answer here is yes, but it expands to
```
def f: Unit =
  ???
end f
```
corresponding to the intention.

**Comment by odersky** [comment]
> Should the compiler allow the following empty def?

I think logically it should not. end markers an optional addition to a program. The program needs to be syntactically correct even if they are missing.

**Comment by SethTisue** [comment]
recent discussion thread https://contributors.scala-lang.org/t/pre-sip-improve-explicit-end-terminator-syntax-for-unit-return/7142
