### ISSUE TITLE
transparent inline def leaks opaque type

### ISSUE THREAD

**Issue by bishabosha** [scala/scala3#14305]
## Compiler version

3.1.0

## Minimized code

```Scala
class Example {
  opaque type Index = Array[Int]
  transparent inline def index(using index: Index): Index = index
}

object Usage {
  def run(example: Example)(using example.Index): Unit = {
    example.index.length
  }
}
```

## Output

Compiles ok

## Expectation

`length` should not be a member of the result of `example.index` when in the scope of `Usage`

**Comment by som-snytt** [comment]
Analogous to qualified private class leaking in a result type, albeit a bad analogy.

**Comment by soronpo** [comment]
Could be a duplicate of https://github.com/lampepfl/dotty/issues/13461

**Comment by nicolasstucki** [comment]
I added it to #13461
