### ISSUE TITLE
Cannot match on `Type` of opaque type with type variable

### ISSUE THREAD

**Issue by prolativ** [scala/scala3#15470]
## Compiler version

3.1.3 and earlier ones

## Minimized code

Macro.scala
```scala
//> using scala "3.1.3"

import scala.quoted.*

object OpaqueScope:
  opaque type MyInt[A] = Int

export OpaqueScope.MyInt

inline def foo() = ${ fooImpl }

def fooImpl(using Quotes) =
  Type.of[MyInt[String]] match
    case '[MyInt[a]] => '{}
```

MacroTest.scala
```scala
def bar = foo()
```

## Output

```scala
[error] ./MacroTest.scala:1:11: Exception occurred while executing macro expansion.
[error] scala.MatchError: Type.of[...] (of class scala.quoted.runtime.impl.TypeImpl)
[error]         at Macro$package$.fooImpl(Macro.scala:14)
[error] 
[error] def bar = foo()
[error]           ^^^
```

## Expectation

The pattern match should succeed, just as it does if one of the changes below is made:
* `MyInt` is declared as a trait or a non-opaque type alias instead of an opaque type alias
* the concrete type `'[MyInt[String]]` is used in the match pattern instead of `'[MyInt[a]]` with a type variable

**Comment by abgruszecki** [comment]
@nicolasstucki We really need to figure out the semantics of matching on types and put a stop on these issues, otherwise the users will start to depend on the current behaviour and we'll have to break their code to fix everything.

**Comment by prolativ** [comment]
Closing in favour of https://github.com/scala/scala3/issues/21889
