### ISSUE TITLE
Add the linter option -Wunused:patvars

### ISSUE THREAD

**Issue by PaulCoral** [scala/scala3#16628]
In the (currently approved) PR #16157 (related to issue #15503), which add some linter options, it was decided not to add `-Wunused:patvars` yet, as it requires modifications to more phases of the compiler. Thus, it seems a better idea to handle it separately.

The current replacement is `-Wunused:unsafe-warn-patvars` which doesn't support suppressing warnings (`x @ _`), thus triggering false positive, i.e. in for expression.

The issue is that it seems not possible to differentiate these cases, after desugaring  :
```scala
case Foo(x)   => ??? // desugared to Foo(x@_)
case Foo(x@_) => ???
```

#### TODO :
- Add `-Wunused:patvars` (which should also be triggered by `-Wunused:all`)
- remove `-Wunused:unsafe-warn-patvars`
- Update the test suits `i15503*.scala`
- Update the help message.

**Comment by Linyxus** [comment]
After discussing this issue on today's LAMP compiler meeting, we decide to close it as not planned.
