### ISSUE TITLE
Higher kind of polymorphic function with dependent type generates weird error information

### ISSUE THREAD

**Issue by tribbloid** [scala/scala3#16756]
## Compiler version

3.2.1

## Minimized code

Starting from the following code

```Scala
class DependentPoly {

  sealed trait Col[V] {

    trait Wrapper
    val wrapper: Wrapper = ???
  }

  object Col1 extends Col[Int]

  object Col2 extends Col[Double]

  val polyFn = [C <: Col[?]] => (x: C) => x.wrapper
}
```

then ask BSP (VSCode + metal) to generate the type annotation of the last line, it will become:

```
  val polyFn: [C <: Col[?]] => (x: C) => x.Wrapper = [C <: Col[?]] => (x: C) => x.wrapper
```

## Output

```scala
Found:    (x.wrapper : x.Wrapper)
Required: x.Wrapper
Note that implicit conversions were not tried because the result of an implicit conversion
must be more specific than x.Wrapper
```

## Expectation

Type annotation added by BSP should always be equal in effect to the original code

and "Found: x.Wrapper; Required: x:Wrapper" really doesn't evoke confidence :->

**Comment by mbovel** [comment]
The problem is that writing the type explicitly introduces two distinct type variables named `C` instead of a single one:

```scala
val polyFn: [C <: DependentPoly.this.Col[?]] => (x: C) => x.Wrapper =
  [C <: Col[?]] => (x: C) => (x.wrapper: x.Wrapper)
```

```
Found:    x.Wrapper
Required: x.Wrapper

Found:    [C <: DependentPoly.this.Col[?]] => (x: C ) => x.Wrapper
Required: [C <: DependentPoly.this.Col[?]] => (x: C²) => x.Wrapper
where:    C  is a type variable with constraint <: DependentPoly.this.Col[?]
          C² is a type variable with constraint <: DependentPoly.this.Col[?]
```

This however works when using the desugared form to define the `PolyFunction`:

```scala
val polyFn2: [C <: Col[?]] => (x: C) => x.Wrapper =
  new PolyFunction:
    def apply[C <: Col[?]](x: C) = x.wrapper
```

Here both `C`s are the same.

**Comment by tribbloid** [comment]
I don't know, I was just following metals :-)

thanks a lot for the discovery, now we can just focus on the type signature difference between the full definition and the shorthand

**Comment by tribbloid** [comment]
Looks like the problem is gone in 3.3.0: https://scastie.scala-lang.org/tribbloid/g0AF18F7QHWkhF0eMEbiAA/11

@mbovel we can close this if the problem has a unit test

**Comment by tribbloid** [comment]
works in 3.5.2: https://scastie.scala-lang.org/jvydIZqlSqShmMDeG7ERWQ

thank you for figuring it out! case closed
