### ISSUE TITLE
Symbol without denotation in ReactiveMongo/ReactiveMongo-BSON

### ISSUE THREAD

**Issue by Kordyjan** [scala/scala3#17346]
## Compiler version

Spotted in 3.3.0-RC4.
It will require additional work to determine if it was happening before. 

## Code

```Scala
//> using scala "3.3.0-RC4-bin-SNAPSHOT"
//> using options "-Wunused:all"
//> using lib "org.reactivemongo::reactivemongo-bson-api:1.1.0-RC9"

import reactivemongo.api.bson.*

case class Eval()

given BSONDocumentHandler[Eval] = Macros.handler
```

## Output

Crash of the compiler. Note that since #17316 missing denotation is not causing a crash.

The symbol that is missing denotation is a self-alias defined [here](https://github.com/ReactiveMongo/ReactiveMongo-BSON/blob/f34cebd78846dc4096866a84f989ed738088f703/api/src/main/scala-3/MacroImpl.scala#L488)

I was trying to reproduce the issue outside of the library but without success. We should return to that and investigate what is going on.

**Comment by WojciechMazur** [comment]
Closing it as it does not crash in 3.3.0 or any other subsequent version
