### ISSUE TITLE
`-Wunused:imports` causes an error on methods that come from an external library

### ISSUE THREAD

**Issue by arainko** [scala/scala3#17394]
## Compiler version
3.3.0-RC5

### Project 1 - the library
```scala
//file AppliedBuilder.scala

package repro

import repro.internal.*

final class AppliedBuilder[Source, Dest](appliedTo: Source) {
  inline def transform: Dest = ReproObject.doNothing
}
```

```scala
//file Extension1.scala
package repro

import repro.internal.*

extension (source: Int) inline def whatever1 = ReproObject.doNothing
```

```scala
//file Extension2.scala
package repro

import repro.internal.*

extension (source: Int) inline def whatever2 = ReproObject.doNothing
```

```scala
//file ReproObject.scala
package repro.internal

private[repro] object ReproObject {
  inline def doNothing = ???
}
```

```scala
//file syntax.scala
package repro

extension [Source](source: Source) {
  def into[Dest]: AppliedBuilder[Source, Dest] = AppliedBuilder[Source, Dest](source)
}
```

```scala
//file project.scala
//> using scala "3.2.2"
//> using publish.organization "repro"
//> using publish.name "repro"
//> using publish.version "0.1.0"
```

### Project 2 - usage site, depends on 'Project 1'
```scala
//file usage.scala

//> using scala "3.3.0-RC5"
//> using option "-Wunused:all"
//> using dep "repro::repro:0.1.0"

import repro.*

@main def main = "whatever".into[Int].transform
```

To reproduce 'Project 1' needs to be published first:
```bash
scala-cli --power publish local .
```

then we can just run the second project with:
```bash
scala-cli compile .
```

## Output

```bash
aleksander@pop-os:~/repos/wunused-usage-repro$ scala-cli compile .
Compiling project (Scala 3.3.0-RC5, JVM)
exception occurred while compiling /home/aleksander/repos/wunused-usage-repro/usage.scala
Error compiling project (Scala 3.3.0-RC5, JVM)
Error: Unexpected error when compiling project_dd4f5f0c18: 'Toplevel definition inline$ReproObject$i1 is defined in
  /home/aleksander/.ivy2/local/repro/repro_3/0.1.0/jars/repro_3.jar(repro/Extension1$package.class)
and also in
  /home/aleksander/.ivy2/local/repro/repro_3/0.1.0/jars/repro_3.jar(repro/Extension2$package.class)
One of these files should be removed from the classpath.'
Compilation failed
```

## Expectation
Compilation succeeds just like it does without `-Wunused:all`

## Context
This issue was first reported here: https://github.com/arainko/ducktape/issues/54 - a workaround for it was moving the contents of [fallibleSyntax.scala](https://github.com/arainko/ducktape/blob/af9769b1685ea3f430d65992a1b3ae610951ef26/ducktape/src/main/scala/io/github/arainko/ducktape/fallibleSyntax.scala) to [syntax.scala](https://github.com/arainko/ducktape/blob/af9769b1685ea3f430d65992a1b3ae610951ef26/ducktape/src/main/scala/io/github/arainko/ducktape/syntax.scala), that way another inline accessor for `Transformations` (with the name `inline$Transformations$i1`) is not generated, a new `inline$Transformations$i3` accessor is generated instead, because these are now in the scope of the same class (`syntax$package`).
For the sake of completeness, here's a [definition of `Transformations`](https://github.com/arainko/ducktape/blob/af9769b1685ea3f430d65992a1b3ae610951ef26/ducktape/src/main/scala/io/github/arainko/ducktape/internal/macros/Transformations.scala), this file houses proxies to macros, it's also package private.

**Comment by chuwy** [comment]
FYI I used ` -Wunused:imports`

**Comment by adpi2** [comment]
Here is a simplified version of this issue without any inline, or inline accessor:

In lib.scala:
```scala
//> using scala 3.3.4
//> using publish.organization "org.example"
//> using publish.name "lib"
//> using publish.version "0.1.0-SNAPSHOT"

package example:
  trait A:
    def foo: String = ???

  trait B:
    extension (x: Int)
      def foo: String = ???

package object example extends A with B
```
In app.scala:
```scala
//> using scala "3.3.4"
//> using option "-Wunused:imports"
//> using dep "org.example::lib:0.1.0-SNAPSHOT"

import example.*

@main def main = foo
```
```
> scala --power publish local lib.scala
> scala compile app.scala
[error] ./app.scala:7:18
[error] Toplevel definition foo is defined in
[error]   /home/piquerez/.ivy2/local/org.example/lib_3/0.1.0-SNAPSHOT/jars/lib_3.jar(example/B.class)
[error] and also in
[error]   /home/piquerez/.ivy2/local/org.example/lib_3/0.1.0-SNAPSHOT/jars/lib_3.jar(example/A.class)
[error] One of these files should be removed from the classpath.
[error] @main def main = foo
[error]       
```

This was inspired by https://github.com/sbt/sbt/issues/7726 in sbt 2

**Comment by som-snytt** [comment]
With 3.5.1 and sbt, the minimal example gives me:
```
[error] -- Error: /home/amarki/projects/i17394-test/src/main/scala/main.scala:4:17 -----
[error] 4 |@main def main = foo
[error]   |                 ^
[error]   |Toplevel definition foo is defined in
[error]   |  /home/amarki/.ivy2/local/org.example/lib_3/0.1.0/jars/lib_3.jar(example/package.tasty)
[error]   |and also in
[error]   |  /home/amarki/.ivy2/local/org.example/lib_3/0.1.0/jars/lib_3.jar(example/A.tasty)
[error]   |One of these files should be removed from the classpath.
[error] one error found
```
without any warnings turned on.

If an interaction with CheckUnused is suspected, I'll try it against my PR, if I can reproduce the issue (that is, compile cleanly without the flags). I confirmed same behavior with bin/scalacQ.

**Comment by adpi2** [comment]
@som-snytt

> without any warnings turned on.

You are right and I have the same behavior on `3.3.4`.

However if you take this other example, it crashes with the `-Wunused:imports` but it succeeds without. Also notice the `given` import: it also compiles successfully if I remove it.

```scala
//> using scala "3.5.1"
//> using option "-Wunused:imports"
//> using dep "org.example::lib:0.1.0-SNAPSHOT"

import example.{given, *}

object C
```

```
> scala --power publish local lib.scala
> scala compile app.scala
Compiling project (Scala 3.5.1, JVM (17))
Error compiling project (Scala 3.5.1, JVM (17))
Error: Unexpected error when compiling scala3-17394_8155ffa868-97a3a2609c: dotty.tools.dotc.core.TypeError$$anon$1: Toplevel definition foo is defined in
  /home/piquerez/.ivy2/local/org.example/lib_3/0.1.0-SNAPSHOT/jars/lib_3.jar(example/package.tasty)
and also in
  /home/piquerez/.ivy2/local/org.example/lib_3/0.1.0-SNAPSHOT/jars/lib_3.jar(example/A.tasty)
One of these files should be removed from the classpath.

Compilation failed
```

It seems the same error is triggered by 3 different things, in the 3 different reproduction cases of this PR.

**Comment by som-snytt** [comment]
Thanks, for `import example.given`, it `imp.expr.tpe.allMembers` per `-Ydebug-error`. Probably the conflict is that collecting members for package objects (`computeMembersNamed`) doesn't take into account the prefix of interest. (Just a guess.)

**Comment by eed3si9n** [comment]
Here's a PR to remove the error - https://github.com/scala/scala3/pull/21975

**Comment by KacperFKorban** [comment]
Should be fixed by https://github.com/scala/scala3/pull/22190

**Comment by som-snytt** [comment]
verified that checkunused also works with the fix.
