### ISSUE TITLE
`-Wconf` and `@nowarn` do not support `origin` filter

### ISSUE THREAD

**Issue by nicolasstucki** [scala/scala3#17538]
## Compiler version

3.3.0-RC4

## Minimized code

```Scala
import scala.collection.Map
import scala.annotation.nowarn

trait MyMap[K, +V] extends Map[K, V] {
  @nowarn("""cat=deprecation&origin=scala\.collection\.Iterable\.stringPrefix""")
  override protected[this] def stringPrefix: String = "MyMap"
}
```

## Output

```scala
-- Warning: t/Test.scala:5:10 --------------------------------------------------
5 |  @nowarn("""cat=deprecation&origin=scala\.collection\.Iterable\.stringPrefix""")
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |          Invalid message filter
  |          unknown filter: origin
-- Deprecation Warning: t/Test.scala:6:31 --------------------------------------
6 |  override protected[this] def stringPrefix: String = "MyMap"
  |                               ^
  |overriding method stringPrefix in trait Iterable of type => String is deprecated;
  |  method stringPrefix of type => String should be removed or renamed.```
```
## Expectation

Should compile without waninings

**Comment by som-snytt** [comment]
More complaining at https://github.com/lampepfl/dotty/issues/19582 with link to chat where it was needed.

**Comment by hamnis** [comment]
Scala 2.13 makes ignoring expected unused imports possible since we can use -Wconf:origin like described here: https://github.com/scala/scala-collection-compat?tab=readme-ov-file#fixing-unused-import-warnings

It would be really great if this could be ported to scala 3.3, so more of the community can turn on -WError

**Comment by som-snytt** [comment]
The PR does deprecations but not yet import warnings; I'll do that after the `CheckUnused` refactor is accepted.
