### ISSUE TITLE
Import exported function from a library loses the default parameters

### ISSUE THREAD

**Issue by JD557** [scala/scala3#17930]
## Compiler version

3.3.0

## Minimized code

lib.scala:
```scala
//> using scala "3.3.0"
//> using publish.name "defaultstest"
//> using publish.organization "eu.joaocosta"
//> using publish.version "0.1.0-SNAPSHOT"

package eu.joaocosta.defaultstest

object Foo {
  def foo(x: Int, y: Int = 5): Int = x + y
}

object Bar {
  export Foo.*
}

object App {
  println(Bar.foo(2)) // Works
}
```

Published with `scala-cli --power publish local .\lib.scala`

app.sc
```scala
//> using scala "3.3.0"
//> using lib "eu.joaocosta::defaultstest::0.1.0-SNAPSHOT"

import eu.joaocosta.defaultstest._

println(Foo.foo(2)) // Works
println(Bar.foo(2)) // Fails with "missing argument for parameter y of method foo in object Bar: (x: Int, y: Int): Int"

```

## Output

```scala
[error] .\app.sc:7:9
[error] missing argument for parameter y of method foo in object Bar: (x: Int, y: Int): Int
[error] println(Bar.foo(2)) // Fails with "missing argument for parameter y of method foo in object Bar: (x: Int, y: Int): Int"
[error]         ^^^^^^^^^^
```

## Expectation

The code should compile, using the default methods (same behavior as `Foo.foo(2)`)

## Notes

This seems very similar to https://github.com/lampepfl/dotty/issues/15031, although in my case the problem happens when importing a library.
No amount of `clean`/`compile` seems to fix it.

**Comment by sbrunk** [comment]
I just ran into this issue as well, while looking into ways to split an API with a many methods with default parameters into manageable chunks, but keeping a single entry-point to call these methods https://github.com/sbrunk/storch/issues/29.

Export clauses seem like the perfect solution here, but given the large number of methods with default parameters, we'll have to wait until we have a fix for this issue.

**Comment by bishabosha** [comment]
This seems like something we can maybe solve similar to constructor proxies (i.e. a constructor proxy is a fake inline `apply` method in a fake exported companion object), we could add fake default accessors to the fake exported companion object

**Comment by lbialy** [comment]
We have the same problem in Besom with exported defaults losing default args.
