### ISSUE TITLE
top level extension method dealiases opaque type in result type

### ISSUE THREAD

**Issue by artembakhanov** [scala/scala3#18097]
## Compiler version

3.3.0

## Minimized code

```Scala
opaque type PositiveNumber = Double

object PositiveNumber:
  extension (x: PositiveNumber)
    def mult1(other: PositiveNumber): PositiveNumber =
      x * other

extension (x: PositiveNumber)
  def mult2(other: PositiveNumber): PositiveNumber =
    x * other

object Test:
  def multMap1[A](x: Map[A, PositiveNumber], num: PositiveNumber): Map[A, PositiveNumber] = x.map((key, value) => key -> value.mult1(num)).toMap

  def multMap2[A](x: Map[A, PositiveNumber], num: PositiveNumber): Map[A, PositiveNumber] = x.map((key, value) => key -> value.mult2(num)).toMap
  def multMap2_2[A](x: Map[A, PositiveNumber], num: PositiveNumber): Map[A, PositiveNumber] = x.map((key, value) => key -> mult2(value)(num)).toMap
```

## Output

```scala
[error] ./foo.scala:15:145
[error] Cannot prove that (A, Double) <:< (A, V2).
[error] 
[error] where:    V2 is a type variable with constraint <: PositiveNumber
[error]   def multMap2[A](x: Map[A, PositiveNumber], num: PositiveNumber): Map[A, PositiveNumber] = x.map((key, value) => key -> value.mult2(num)).toMap
[error]
```

## Expectation
I would expect both functions be defined without type error. For some reason, when an opaque type is not a top-level definition, there is no type error when defining these functions.

**Comment by som-snytt** [comment]
`mult1` errors in the same compilation unit, and `mult2` errors in a different compilation unit (as shown).

That is so weird, that I assume I must have tested it wrong.

**Comment by bishabosha** [comment]
so for some reason PositiveNumber is being de-aliased to `Double` when `mult2` is used in another scope

**Comment by odersky** [comment]
This needs a minimization to be sure, right now there is way too much type inference going on for a good diagnosis.

**Comment by ghostbuster91** [comment]
I think I have a simpler reproducer for the same issue: https://scastie.scala-lang.org/YRmAX35aTyO8mEoIM1kgRw this only happens if the extensions method has the same name as native method on the wrapped type.

**Comment by warjort** [comment]
I am also seeing this problem with 3.3.1, 3.3.2-RC2, 3.4.0-RC1

This is my minimization.

Opaque class:
```Scala
package test

type Foo = Unit
val bar: Foo = ()

//object Foo {
opaque type Opaque = Unit

extension (foo: Foo)
  def go: Option[Opaque] = ???
//}
```

Test class:
```Scala
package test

//import Foo.*

final case class Test(value: Opaque)

def test: Test =
  //go(bar) match
  bar.go match
    case Some(value) => Test(value)
    case _           => ???
```

Incorrect compiler error:
```
Found:    (value : Unit)
Required: test.Opaque
```

The above includes 2 different (commented out) workarounds:
* Put the opaque type and the extension method in a non top level scope
* Call the extension method as a function instead of using selector syntax

**Comment by warjort** [comment]
NOTE: I originally saw this problem in a slightly different context. But I assume it is the same?

My extension method was returning an anonymous tuple inside an Option.
```scala
Option[(Opaque, A)]
```
here a third workaround was to use a case class instead of the tuple
```scala
Option[Result[A]]
// with
final case class Result[A](value: Opaque, a: A)
```
Is this because the opaque type is not explicitly mentioned in the return type?
