### ISSUE TITLE
Spurious "unused local definition" for type parameter of polymorphic function within a block

### ISSUE THREAD

**Issue by felher** [scala/scala3#18388]
Hey all,

thank you so much for your amazing work and bringing warnings back. I might have found some spurious warning:

## Compiler version

3.3.0 and 3.3.1-RC1

## Minimized code

```Scala
  {
    def func(pred: [A] => A => Boolean): Unit =
      val _ = pred
      ()

    val _ = func
  }

```

The `val _ = ...` stuff is just here to silence the warnings that might otherwise pop up, like `pred` being unused.

## Output

```
[warn] -- Warning: /tmp/test/src/main/scala/Main.scala:3:20 ---------------------------
[warn] 3 |    def func(pred: [A] => A => Boolean): Unit =
[warn]   |                    ^
[warn]   |                    unused local definition
```

## Expectation

Should not warn.

## Scastie-Link:
https://scastie.scala-lang.org/JYhAvR0gQlKcAFTb9eOsFA

( Contains more newlines than normal to make it easy to spot which part the compiler considers to be unused )

**Comment by som-snytt** [comment]
Fixed in 3.3.2 by https://github.com/scala/scala3/pull/17929

Bisected on scastie. I wonder why scastie doesn't have a bisect button.

I'll add the small test to the existing test, since it's not an obvious duplicate.

```
            DefDef(func,
              List(List(
                ValDef(pred,
                  RefinedTypeTree(TypeTree(), List(
                    DefDef(apply,
                      List(
                        List(
                          TypeDef(A,
                            TypeBoundsTree(TypeTree(), TypeTree(),
                              Thicket(List()))
                          )
                        ),
                      List(ValDef(x$1, Ident(A), Thicket(List())))),
                      Ident(Boolean), Thicket(List()))
                  )),
                Thicket(List()))
              )),
```
