### ISSUE TITLE
Add contextual method types to Quotes API

### ISSUE THREAD

**Issue by nicolasstucki** [scala/scala3#18477]
Hmm, interesting... It looks like the compiler internally uses `ContextualMethodType` rather than just `MethodType` to express a method with `(using ...)` parameters clause but currently there seems no way to create contextual methods from the quotes' reflect API. @nicolasstucki are there any plans to add this functionality in the nearest future?

_Originally posted by @prolativ in https://github.com/lampepfl/dotty/discussions/14056#discussioncomment-6845567_

**Comment by rssh** [comment]
related old issue:  https://github.com/lampepfl/dotty/issues/17663
