### ISSUE TITLE
Add a flag that enables all linting

### ISSUE THREAD

**Issue by szymon-rd** [scala/scala3#18559]
Having a flag enabling all the linting options at once would be helpful. More and more linting is being added, and writing all the flags can make the compile command long. It is also a standard user path to enable all the linting options.

**Comment by som-snytt** [comment]
The topic of research is what to name it.

I previously tried legacy `-Xlint` https://github.com/lampepfl/dotty/pull/14753

Conforming `-Wlint` isn't pronounceable.

Maybe there is a linguist at EPFL.

**Comment by SethTisue** [comment]
fwiw, gcc uses `-Wall` (and has for donkey's years)

**Comment by som-snytt** [comment]
I happen to be reading Moby-Dick, `-Wal`.
