### ISSUE TITLE
conflicting instances with inheritance from case class

### ISSUE THREAD

**Issue by SimonGuilloud** [scala/scala3#18552]
## Compiler version

Tested with 3.2.1 and 3.3.1

## Minimized code

```Scala
trait A
trait B extends A

trait M[+T]

case class MA(id:Int) extends M[A]
class MB(id:Int)  extends MA(id) with M[B]
```

## Output

```scala
illegal inheritance: class MB inherits conflicting instances of non-variant base trait M.

  Direct basetype: M[Playground.B]
  Basetype via case class MA: M[A]
```

## Expectation

Compiles, or meaningful error message. If `MA` is not a case class, the code compiles. The base trait `M` is not non-variant.

**Comment by soronpo** [comment]
Compiles successfully on 2.13

**Comment by SimonGuilloud** [comment]
I accidentally rediscovered the bug while forgetting it was reported already. Does someone have an idea of a workaround other than implementing manually all the functions of case classes?

**Comment by EugeneFlesselle** [comment]
@SimonGuilloud  not sure if it would be suitable for your use case, but you _can_ do:
```scala 3
trait M:
  type T

case class MA(id:Int) extends M:
  type T <: A
class MB(id:Int) extends MA(id):
  type T <: B
```
