### ISSUE TITLE
`-Wconf` `src` filter not implemented

### ISSUE THREAD

**Issue by povder** [scala/scala3#18782]
## Compiler version

3.3.1

---

Scala 2's `-WConf` filters include `src` filter which allows configuring warnings for a given source path pattern. It is missing in Scala 3. It is handy for ignoring warnings for generated sources where you have no option of placing `@nowarn` annotations.  Right now I'm facing a problem were I can't enable `-Werror` because of warnings reported in generated sources (in my case generated by ScalaPB protobuf compiler).

It would be great to bring all Scala2 `WConf` filters to Scala 3 but this issue is just about `src`. I am willing to contribute a pull request for this.

**Comment by som-snytt** [comment]
Duplicates https://github.com/lampepfl/dotty/issues/17634 which was deemed not regressive enough to warrant a ticket without further discussion.

**Comment by povder** [comment]
Ah ok I didn't realize that before opening an issue I am supposed to search in resolved tickets as well.

**Comment by som-snytt** [comment]
I remembered because someone commented on the discussion that they would like to fix it, but of course they will need an open ticket! So your timing is impeccable.

**Comment by henricook** [comment]
Thanks for this @povder! I was looking it up because the issue prevents me using Play with Scala 3, so this is very well timed for me personally :-D
