### ISSUE TITLE
Scaladoc generates broken local links

### ISSUE THREAD

**Issue by dixine55** [scala/scala3#19208]
As of currently, when you generate documentation for your library, the links that are generated are not clickable locally.
I believe that this is due to that the network request made by jQuery is denied because of a CORS error, which is seen in the network tab.
![error](https://github.com/lampepfl/dotty/assets/10165673/ad9c569a-9ee7-4ed5-b742-c6b7525d98a6)

## Compiler version
sbt:> print scalaVersion
3.3.0

## Minimized code

scala-cli doc .
sbt doc

Both generations will lead to broken local links, I have **not been able to generate it and try with Scaladoc directly**, no matter what I've attempted as an arg to Scaladoc I get "The system cannot find the path specified.", but since both scala-cli and sbt doc are based on Scaladoc I feel pretty confident it's an issue with Scaladoc itself.

## Output

Directory with 
packageName/
fonts/
hljs/
images/
scripts/
styles/
webfonts/
packageName.html
favicon.ico
index.html
scaladoc.version (3.3.0)

And when you open packageName.html or index.html or any of the html files in packageName/* the linking doesn't work.

## Expectation
I believe it should work out of the box, or it feels really weird for it not to..

But, in order to fix it I made this code that does _almost_ patch all the links perfectly, I tried to understand how Scaladoc works by itself, but it's over my paygrade.

So if it is a bug and/or if we could add it as a feature to build it locally by passing an argument -local, that'd be very helpful to people that don't know how to boot up a webserver and configure headers.

Link to the program that fixes the links:
https://github.com/dixine55/Scaladoc-Local-Version-Patcher

Edit; As som-snytt pointed out I missspelled Scaladoc as scalaDoc, changed it so it's consistent.

**Comment by som-snytt** [comment]
> how scalaDoc works

Someone will say "Scaladoc", so it might as well be me. I don't know why it departs from "JavaDoc".

I don't know why an option would be needed, in the sense that URLs should just work. Scaladoc tool is always unexpectedly complex. I would expect the complexity at runtime, to support its useful features.

**Comment by dixine55** [comment]
Thank you for pointing out that inconsistency, fixed it now!

I agree that it'd be good if it worked straight out of the box, but as I haven't really developed a good enough understanding of how the code interacts in the grand scheme of thing, I was suggesting the "-local" option in case there is no "two world"-solution where it works both for local and online deployment right away. I assume that the majority who use the tool will end up uploading it online anyway and therefore wouldn't want to tweak around too much with it, but then again, there's also cases where you want to try building it locally first..

**Comment by bjornregnell** [comment]
I think it should "Just work" out of the box for both local and server deployment, if possible, without any configs etc. If configs are needed it should work for local and require setting fro server as local is the simple use case for beginners.

**Comment by Math-ias** [comment]
[This is the important code path here.](https://github.com/scala/scala3/blob/64411b6d0d3ce716a9dbdf73d871981544eac95f/scaladoc/resources/dotty_res/scripts/ux.js#L175) It is making a GET request to whatever's linked. It then downloads the content and replaces the page's contents. I suppose one of the benefits is that a lot of assets don't have to get reloaded. That may make it feel snappier.

It's not necessarily related to removing jQuery, though jQuery is used to make the GET request. I will post changes to restore functionality when browsing locally.
