### ISSUE TITLE
Error `no member new scala.beans.BeanProperty . <init>` under first incremental compilation

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#19421]
Failure found in OpenCB for `j5ik2o/akka-persistence-s3` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/7481844264/job/20364298922)

When compiling project for the first time it can fail with no `BeanPropert` constructor. When compiling for the second time it is able to finish compilation.

## Compiler version
Last good release: 3.4.0-RC1-bin-20231115-0420aaf-NIGHTLY
First bad release: 3.4.0-RC1-bin-20231116-fdf8de3-NIGHTLY
Bisect points to d04b3c704022ea3ccf93fb082c17e657374cec4d
Present in 3.4.0-RC1, not present in 3.3.2-RC1

## Minimized code

No minimisation. The project itself does not use `@BeanProperty`, it might be used somewhere in the upstream. 
To reproduce: 
```bash
git clone https://github.com/j5ik2o/akka-persistence-s3.git -b v1.2.177 repo
cd repo 
sbt "++${ScalaVersion};clean;Test/compile"
```

## Output
One of projects would fail with:
```scala
[error] no member new scala.beans.BeanProperty . <init>
[error] value <none>: <notype> does not take parameters
[error] two errors found
[error] (journal / Test / compileIncremental) Compilation failed```
```

## Expectation
Data race? should be fixed to prevent spurious failures

**Comment by xuwei-k** [comment]
same error in my private repo 😢

**Comment by nicolasstucki** [comment]
The issue in this case happens when loading `actor` https://github.com/akka/akka/blob/v2.9.1/akka-actor/src/main/scala/akka/actor/Actor.scala#L113. This definition is skipped here https://github.com/lampepfl/dotty/commit/d04b3c704022ea3ccf93fb082c17e657374cec4d#diff-9919eb5ea021e001a170f43b5f56fbab5e79aaadfeb947b2974a533f116b9e84R454. If we do not skip it we fix the issue. The complication is that we do not know the annotations when we create the symbol.

**Comment by nicolasstucki** [comment]
#### Minimization 

[i19421.zip](https://github.com/lampepfl/dotty/files/14040619/i19421.zip)

```
$ sbt "clean; Test/compile"
...
[error] no member new scala.beans.BeanProperty . <init>
[error] value <none>: <notype> does not take parameters
[error] two errors found
```

**Comment by nicolasstucki** [comment]
### Minimization

`project/build.properties`
```
sbt.version = 1.6.2
```

`build.sbt`
```scala
lazy val root = (project in file("."))
  .settings(
    scalaVersion := "3.4.0",
    libraryDependencies ++= Seq(
      "com.typesafe.akka" %% "akka-persistence-tck" % "2.8.0"
    ).map(_.cross(CrossVersion.for3Use2_13))
  )
```

`src/main/scala/S3SnapshotStoreSpec.scala`
```scala
import com.typesafe.config.Config
import akka.persistence.snapshot.SnapshotStoreSpec

object ConfigHelper {
  def config(): Config = ???
}

class S3SnapshotStoreSpec extends SnapshotStoreSpec(null)
```

```
$ sbt "clean; compile; clean; compile"
```
