### ISSUE TITLE
Possible bug in unused imports when it comes to relative imports

### ISSUE THREAD

**Issue by keynmol** [scala/scala3#19653]
Here's a reproducer:

```scala
//> using scala 3.4.0-RC3
//> using option -Wunused:all

import scala.util.boundary // this import is not marked as unused
import boundary.break // this import IS marked as unused

@main def hello = ???
```

It is perhaps a philosophical question - should unused imports compute some sort of relative imports closure and invalidate all imports?

Because _technically_ `boundary` is used, if you evaluate strictly top to bottom.

**Comment by som-snytt** [comment]
Philosophically, if an import is used only by an unused element (such as a def), it could be reported that way.
```
import concurrent.Future
@unused private def f = Future(42)
```
When there are large blocks of imports, this could be useful and not too much mechanism.

**Comment by SethTisue** [comment]
I agree with Nicolas that the current behavior is correct.

it's possible that something like @som-snytt's idea would be useful, but it doesn't seem like a priority, and we generally don't keep open tickets on well-maybe-someday-we-might-do-something-in-this-space
