### ISSUE TITLE
strange error for missing `using` keyword in implicit argument

### ISSUE THREAD

**Issue by Dieken** [scala/scala3#19680]
## Compiler version

3.3.1  and 3.4.0-RC4.

## Minimized example

```Scala
@main
def main(args: String*): Unit =
  println("hello")
  val config = Config(8080, "docs.scala-lang.org")
  given Config = config
  println(renderWebsite("/home")(config))

case class Config(port: Int, baseUrl: String)

def renderWebsite(path: String)(using config: Config): String =
  "<html>" + renderWidget(List("cart")) + "</html>"

def renderWidget(items: List[String])(using config: Config): String =
  "<div>" + items.mkString(
    ", "
  ) + s" ${config.port} ${config.baseUrl}" + "</div>"

```

## Output Error/Warning message

```scala
-- [E007] Type Mismatch Error: /private/tmp/a.scala:6:33 -----------------------
6 |  println(renderWebsite("/home")(config))
  |                                 ^^^^^^
  |                                 Found:    (config : Config)
  |                                 Required: Int
  |
  | longer explanation available when compiling with `-explain`
1 error found
Errors encountered during compilation
```

## Why this Error/Warning was not helpful

Obviously the error message is wrong.

## Suggested improvement

It should remind me removing the whole argument or adding keyword `using` in line 6.

**Comment by som-snytt** [comment]
The message is not wrong, but it would be nice to use the `Did you mean...?` idiom to add that there was an implicit arg (in last position) in the application of the same type.
```
Did you mean `using config`? The application already includes a given Config.
```
It would also be nice for the more usual failure case where there is no given in scope.
```
Did you mean `using config`? The application requires a given Config.
```
Migrating a code base from `implicit` is likely to encounter this mistake.

**Comment by odersky** [comment]
I think this is a very special case, and one that would likely detract from the true source of errors in 99.9% of the cases. So I am against making a special "did you mean" for this. 

On the other hand, even without the implicit parameter complication, the error message is a bit baffling:
```
                                Found:    (config : Config)
                                Required: Int
```
Where does the `Int` come from? I think we should try to explain that it is the `apply` method of the result type of `renderWebSite`. Something like:
```
                                Found:    (config : Config)
                                Required: Int

                                The required type comes from the `apply` method of `String`,
                                which is the result type of `renderWebSite`
```
Or alternatively, show the full expanded call (but this might become very large sometimes).

**Comment by som-snytt** [comment]
The challenge is to report something in brief (and not under `-explain`).

Maybe just for the case of "arg of correct type for some parameter in the expression (but perhaps lacks `using`)" then give the OP the suggested improvement (in some form, perhaps just the expansion).

The required type is just misdirection. (Reminiscent of errors from the days of postfixOps, a puzzler.)

I don't know if OP is in 0.1% of users.

**Comment by mbovel** [comment]
This issue was picked for the Issue Spree of March 19th, 2024. @mbovel, @iusildra, @jan-pieter will be working on it. If you have any insight into the issue or guidance on how to fix it, please leave it here.

**Comment by mbovel** [comment]
It's not clear to me how the info about the expected type should flow from `FunProto.typedArg` to the point where we throw the message, as it seems we don't have this info starting from `Typer.adapt`.

**Comment by mbovel** [comment]
> The challenge is to report something in brief (and not under `-explain`).

My PR unfortunately currently only adds the message under `-explain` because I am afraid it could show it too many cases otherwise. I hope this can still be useful.
