### ISSUE TITLE
Regression in `devsisters/shardcake` for type inference

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#19685]
Based on Open CB failure in `devsisters/shardcake`, [build logs](https://github.com/VirtusLab/community-build3/actions/runs/7850604380/job/21429343488)

I'm not what was the policy about type inference bugs, feel free to close this issue if you it is assumed that there is no guarantee about result type for inference including either `Any` or `Nothing`

## Compiler version
3.4.0-RC-nightly
Bisect points to 6c556aa35a25a9aa785367354f0f96b7a1baa09c

## Minimized code

```Scala
type UIO[+A] = ZIO[Any, Nothing, A]
type URIO[-R, +A] = ZIO[R, Nothing, A]

sealed trait ZIO[-R, +E, +A] {
  final def withFinalizer[R1 <: R](finalizer: A => URIO[R1, Any]): ZIO[R1, E, A] = ???
  final def map[B](f: A => B): ZIO[Any, E, B] = ???
  def flatMap[R1 <: R, E1 >: E, B](k: A => ZIO[R1, E1, B]): ZIO[R1, E1, B] = ???
}
object ZIO:
  def foreachDiscard[R, E, A](as: => Iterable[A])(f: A => ZIO[R, E, Any]): ZIO[R, E, Unit] = ???

sealed abstract class ZLayer[-RIn, +E, +ROut]
def scoped[R]: ScopedPartiallyApplied[R] = ???
class ScopedPartiallyApplied[R](private val dummy: Boolean = true) extends AnyVal {
  def apply[E, A](zio: => ZIO[R, E, A]): ZLayer[R, E, A] = ???
}

abstract class Fiber[+E, +A]

class Synchronized[A]:
  def get: UIO[A] = ???
object Synchronized:
  def make[A](a: => A): UIO[Synchronized[A]] = ???

class Pods(
    connections: Synchronized[Seq[Fiber[Throwable, Nothing]]]
)

def live: ZLayer[_, Throwable, Pods] = scoped {
  // Infers to: ZIO[Any, Nothing, Synchronized[Seq[Fiber[Throwable, Any]]]]
  // Should to: ZIO[Any, Nothing, Synchronized[Seq[Fiber[Throwable, Nothing]]]]
  val x = Synchronized
    .make(Seq.empty[Fiber[Throwable, Nothing]])
    .withFinalizer(_.get.flatMap(connections => ZIO.foreachDiscard(connections)(_ => ???)))
  x.map(new Pods(_))
}
```

## Output

```scala
[error] ./main.scala:35:18
[error] Found:    (_$3 : Synchronized[Seq[Fiber[Throwable, Any]]])
[error] Required: Synchronized[Seq[Fiber[Throwable, Nothing]]]
[error]   x.map(new Pods(_))
[error]                  ^
```

**Comment by odersky** [comment]
I think we should look art each regression. 

I did that here, and found that the new mechanism indeed works here. I see debug output

> forced instantiation of invariant A = Seq[Fiber[Throwable, Nothing]], improved to Seq[Fiber[Throwable, (param)1]]

That looks in principle like an improvement, but in this case the program wanted to see a `Nothing` instead. I think there's nothing we can do, so I am closing this.

**Comment by WojciechMazur** [comment]
Thank you for Martin for explenation!
@devsisters you might be interested in this issue.
