### ISSUE TITLE
Re-merge binary literals

### ISSUE THREAD

**Issue by Kordyjan** [scala/scala3#19695]
Binary literals PR should be re-merged in time for 3.5 release.

https://github.com/lampepfl/dotty/pull/19405

**Comment by odersky** [comment]
Why? I though they need a minor release?

**Comment by SethTisue** [comment]
"before 3.5" is a bit ambiguous — presumably "in time for 3.5" was meant here.

**Comment by nicolasstucki** [comment]
I updated the milestone in #19405 to 3.5 to avoid confusion.

**Comment by odersky** [comment]
Ah indeed I misunderstood. So with the milestone added, can we close this issue now?

**Comment by Sporarum** [comment]
Thinking more about it, shouldn't they be added as experimental first, validated by the SIP comittee, and only then merged as non-experimental ?

(I think it is fine to do an exception for this case, but it is good to be aware that this is what we are doing)

**Comment by Kordyjan** [comment]
That should be the procedure, but as far as I remember, there are problems with experimental switches during parsing.

**Comment by odersky** [comment]
Not for language imports. We do honor them during parsing. But in this case, since the SIP is already accepted, we don't need to go though the procedure again.

**Comment by Sporarum** [comment]
Out of curiosity, do we honor them as well during tokenization ?

(That is where the parsing of integer literals is done)

**Comment by Gedochao** [comment]
It has been decided to be included in the 3.5.0 release.
