### ISSUE TITLE
Allow `var` in refinements

### ISSUE THREAD

**Issue by odersky** [scala/scala3#19809]
## Minimized example

```Scala
  type A = Any { var x: Int }
```

## Output

```
1 |  type A = Any { var x: Int }
  |                 ^^^^^^^^^^
  |                 refinement cannot be a mutable var.
  |                 You can use an explicit getter x and setter x_= instead
```

## Expectation

Expand the refinement to 
```scala
type A = Any { def x: Int, def x_=($x: Int): Unit }
```
instead.

That's what Scala 2 does. See also: https://contributors.scala-lang.org/t/why-is-there-a-restriction-on-refinements-not-having-vars/6498/6

To fix this, we need to touch the following pieces of code:

 - Both versions of syntax.md, to allow the new syntax
 - The parser, make sure the new syntax also shows up as a doc comment of the parsing method
 - Code in Desugar that does the expansion.

**Comment by odersky** [comment]
This is a good Spree ticket, but if someone wants to pick it up before, please go ahead.

**Comment by hamzaremmal** [comment]
I will pick it up for the next Spree. 

cc @mbovel

**Comment by mbovel** [comment]
This issue was picked for the Issue Spree of March 19th, 2024. @hamzaremmal, @aherlihy will be working on it. If you have any insight into the issue or guidance on how to fix it, please leave it here.
