### ISSUE TITLE
Cannot find method `IndexedSeqView.updated` when running a program compiled with CC stdlib

### ISSUE THREAD

**Issue by Linyxus** [scala/scala3#19819]
## Compiler version

`main`

## Minimized code

```Scala
object Hello extends App {
    println(Vector(1, 2, 3).view.updated(1, 8))
}
```

Steps to reproduce (assuming that the code is saved as `Hello.scala`):
```
sbt> set ThisBuild/Build.scala2Library := Build.Scala2LibraryCCTasty
sbt> scala3-bootstrapped/scalac Hello.scala
sbt> scala3-bootstrapped/scala Hello
```

## Output

```scala
Exception in thread "main" java.lang.NoSuchMethodError: 'scala.collection.View scala.collection.IndexedSeqView.updated(int, java.lang.Object)'
	at Hello$.<clinit>(Hello.scala:2)
	at Hello.main(Hello.scala)
```

## Expectation

It should run.

**Comment by odersky** [comment]
I think it's because at runtime we use the normal stdlib, where there is no `updated` in `IndexedSeqView`. Can you try to make the `updated` that we added an inline method?

**Comment by nicolasstucki** [comment]
This is the difference in the bytecode
```diff
  44: invokestatic  #54                 // Method scala/runtime/BoxesRunTime.boxToInteger:(I)Ljava/lang/Integer;
- 47: invokeinterface #60,  3           // InterfaceMethod scala/collection/IndexedSeqView.updated:(ILjava/lang/Object;)Ljava/lang/Object;
+ 47: invokeinterface #60,  3           // InterfaceMethod scala/collection/IndexedSeqView.updated:(ILjava/lang/Object;)Lscala/collection/View;
  52: invokevirtual #64                 // Method scala/Predef$.println:(Ljava/lang/Object;)V
```

**Comment by odersky** [comment]
Which is which?

**Comment by nicolasstucki** [comment]
The one that returns a View is using the CC library. That signature corresponds to the addition new override added in https://github.com/lampepfl/dotty/pull/19798/files#diff-1557066ce6e57518a7fa5d6138de6a2a431ecc6baf30fcf1e423c73cf99b340eR51

Inlining it seems to work (#19824). It is not an ideal solution as it will duplicate the implementation of `updated` at each call site.

**Comment by odersky** [comment]
Or maybe we can massage the return type by going through some abstract type. E.g.

    type C[T] <: T
    def updated(...): C[View]

Would that work?

**Comment by Linyxus** [comment]
> Or maybe we can massage the return type by going through some abstract type. E.g.
> 
> ```
> type C[T] <: T
> def updated(...): C[View]
> ```
> 
> Would that work?

We have to say `type C[T] >: T <: T` to make it typecheck. I tried and it didn't work.

I attempted another fix [here](https://github.com/dotty-staging/dotty/commit/5b1b97933582e70a24e2512dbd99d9c90b874d7f). Do you think that is a good idea?

**Comment by Linyxus** [comment]
I confirm that it works. So maybe we could use this scheme for other methods that need to be added as well?
