### ISSUE TITLE
ClassCastException when using external library due to wrong type assigned at erasure phase

### ISSUE THREAD

**Issue by straszydlo** [scala/scala3#19817]
## Compiler version
3.3.1

## Minimized code
```scala
//> using scala 3.3.1
//> using dep "com.softwaremill.common::tagging:2.3.4"
package test.me

import com.softwaremill.tagging.*

trait Foo
@main def main =
  (new Foo {}).taggedWith[Int]
```
Run with scala-cli: `scala-cli TestMe.scala`, assuming the code is in `TestMe.scala`
## Output

```scala
$ scala-cli TestMe.scala
Exception in thread "main" java.lang.ClassCastException: class test.me.TestMe$package$$anon$1 cannot be cast to class com.softwaremill.tagging.package$Tag (test.me.TestMe$package$$anon$1 and com.softwaremill.tagging.package$Tag are in unnamed module of loader 'app')
        at test.me.TestMe$package$.main(TestMe.scala:9)
        at test.me.main.main(TestMe.scala:8)
```

Interestingly enough, when I compile it with `-Xprint:erasure` flag, I get this output:
```scala
$ scala-cli compile TestMe.scala -Xprint:erasure
Compiling project (Scala 3.3.1, JVM (17))
[[syntax trees at end of                   erasure]] // /home/straszydlo/buggy-bug-reproduction/TestMe.scala
package test.me {
  @SourceFile("TestMe.scala") trait Foo() extends Object {}
  final lazy module val TestMe$package: test.me.TestMe$package = new test.me.TestMe$package()
  @SourceFile("TestMe.scala") final module class TestMe$package() extends Object() {
    private def writeReplace(): Object = new scala.runtime.ModuleSerializationProxy(classOf[test.me.TestMe$package])
    @main def main(): com.softwaremill.tagging.package.Tag =
      {
        val ev$1: ErasedValueType(com.softwaremill.tagging.package.Tagger, test.me.Foo) =
          com.softwaremill.tagging.Tagger(
            {
              final class $anon($outer: test.me.TestMe$package) extends Object(), test.me.Foo {
                private val $outer: test.me.TestMe$package
                final def test$me$TestMe$package$_$$anon$$$outer(): test.me.TestMe$package = $outer
              }
              new Object with test.me.Foo {...}(this):test.me.Foo
            }
          ).asInstanceOf[ErasedValueType(com.softwaremill.tagging.package.Tagger, test.me.Foo)]
        com.softwaremill.tagging.Tagger.taggedWith$extension(ev$1).asInstanceOf[com.softwaremill.tagging.package.Tag]
      }
  }
  @SourceFile("TestMe.scala") final class main() extends Object() {
    <static> def main(args: String[]): Unit =
      try
        {
          test.me.TestMe$package.main()
          ()
        }
       catch
        {
          case error @ _:scala.util.CommandLineParser.ParseError => scala.util.CommandLineParser.showError(error)
        }
  }
}

Compiled project (Scala 3.3.1, JVM (17))
```
We can see that the main method has wrong return type: `@main def main(): com.softwaremill.tagging.package.Tag =  //...`

However, the only change required to make this code work is to remove the package:
```scala
//> using scala 3.3.1
//> using dep "com.softwaremill.common::tagging:2.3.4"
import com.softwaremill.tagging.*

trait Foo 
@main def main =
  (new Foo {}).taggedWith[Int]
```

Now it runs without `ClassCastException`, and printing the code after erasure yields:
```scala
$ scala-cli compile TestMe.scala -Xprint:erasure 
Compiling project (Scala 3.3.1, JVM (17))
[[syntax trees at end of                   erasure]] // /home/straszydlo/buggy-bug/reproduction/TestMe.scala
package <empty> {
  @SourceFile("TestMe.scala") trait Foo() extends Object {}
  final lazy module val TestMe$package: TestMe$package = new TestMe$package()
  @SourceFile("TestMe.scala") final module class TestMe$package() extends Object() {
    private def writeReplace(): Object = new scala.runtime.ModuleSerializationProxy(classOf[TestMe$package])
    @main def main(): Foo =
      {
        val ev$1: ErasedValueType(com.softwaremill.tagging.package.Tagger, Foo) =
          com.softwaremill.tagging.Tagger(
            {
              final class $anon($outer: TestMe$package) extends Object(), Foo {
                private val $outer: TestMe$package
                final def TestMe$package$_$$anon$$$outer(): TestMe$package = $outer
              }
              new Object with Foo {...}(this):Foo
            }
          ).asInstanceOf[ErasedValueType(com.softwaremill.tagging.package.Tagger, Foo)]
        com.softwaremill.tagging.Tagger.taggedWith$extension(ev$1).asInstanceOf[Foo]
      }
  }
  @SourceFile("TestMe.scala") final class main() extends Object() {
    <static> def main(args: String[]): Unit =
      try
        {
          main()
          ()
        }
       catch
        {
          case error @ _:scala.util.CommandLineParser.ParseError => scala.util.CommandLineParser.showError(error)
        }
  }
}

Compiled project (Scala 3.3.1, JVM (17))
```

Also specifying `Unit` type as the `main` method's return type causes the code to execute correctly without the `ClassCastException`, with or without specifying the package:
```scala
//> using scala 3.3.1
//> using dep "com.softwaremill.common::tagging:2.3.4"
package test.me

import com.softwaremill.tagging.*

trait Foo 
@main def main: Unit =
  (new Foo {}).taggedWith[Int]
```

Reproduced with `scala-cli` versions 1.1.2 and 1.1.3 from [here](https://scala-cli.virtuslab.org/install).

## Expectation
All of these snippets should execute without any exceptions.

**Comment by dwijnand** [comment]
@smarter I seem to remember this coming up before and you explaining how the type casting is to blame.  Do you remember which issue it is?

**Comment by sjrd** [comment]
`taggedWith` performs a cast:
https://github.com/softwaremill/scala-common/blob/dfa96871f203ff753cd9c99af493739f737ace0c/tagging/src/main/scala/com/softwaremill/tagging/package.scala#L24-L30
to an intersection of `T` and `Tag`. Since `new Foo {}` is not a value of the trait `Tag`, that is an invalid cast. From there the compiler can do whatever; it's all undefined behavior. In particular, it is at liberty to use `Tag` as the erased type of the thing, right there or elsewhere, and therefore to throw a CCE.

**Comment by sjrd** [comment]
This can be caused by the tie-break rule for the erasure of intersection types. When all else is equal between `A` and `B`, there is a tie-break based on comparing their full names. Putting `Foo` inside a package changes its full name, and therefore potentially changes its relative ordering wrt. `Tag` according to that tie-break.

**Comment by straszydlo** [comment]
@sjrd you're right about the ordering - if I change the package to `Foo.me` (or whatever is lexicographically before `Tag`), it's enough to make the `ClassCastException` disappear. However it's still not consistent with the behavior of the code with `abstract class Foo` instead of `trait Foo` - which does not throw at all. Is the tie-break rule different for traits and abstract classes, or does it not apply at all there?

**Comment by straszydlo** [comment]
@sjrd so this is expected behavior? If yes, then is there any way of working around that without changing the assumption that `Foo` is a trait and `Tag` comes from external library?

**Comment by dwijnand** [comment]
Is there a reliable way _with_ changing the library?  Is the answer, use opaque types, and possibly try to cross-build with opaque types for Scala 3 and the tagging thing for Scala 2?

Otherwise, non-unexpected behaviour.

**Comment by sjrd** [comment]
Yes, an opaque type alias seems the way to go.

**Comment by straszydlo** [comment]
Okay, then a different library it is. Thank you all for the explanation!

**Comment by tmccombs** [comment]
> Yes, an opaque type alias seems the way to go.

How would that work for the tagging use case? An opaque alias is, well, opaque. I want the tagged type to still expose the API of the intended trait/class. I.e. I effectively want the type to be `Foo & Tag`.

**Comment by tmccombs** [comment]
I figured out a generic way to tag a type without casting using opaque types:

```scala
object Tagging {
  opaque type Tag[T] = Any
  opaque type @@[C, T] <: C & Tag[T] = C

  extension [C](obj: C) {
    def taggedWith[T]: C @@ T = obj
  }
}
```

Although I'm not sure if that is usable from scala 2 code.
