### ISSUE TITLE
⚠️ In Progress: transfer of the repo to scala/scala3

### ISSUE THREAD

**Issue by hamzaremmal** [scala/scala3#19848]
All in the title.

**Comment by soronpo** [comment]
This will break the universe, but better late than never 🥲

**Comment by sjrd** [comment]
:warning: PSA: Tomorrow Wednesday March 6 between 9:30am and 11am CET (starting 12:30am in San Francisco, 3:30am in New York, 5:30pm in Tokyo), we will transfer the `lampepfl/dotty` repository to `scala/scala3`.

During that operation, the CI will not be operational. Any in-progress job will be canceled as we start the transfer. Please do not attempt to restart jobs. Avoid submitting PRs or pushing to branches with open PRs during the operation. Once the repo has been transferred and the CI is back online, existing PRs will need to be rebased on the latest `main` if they want a new CI run.

GitHub will automatically redirect HTTPS and git requests, so no immediate action will be required from your side for your links to keep working.

We will post a new message here when we start and finish.

Sorry for the disturbance, and thank you for your understanding.

**Comment by soronpo** [comment]
> I may be taking a joking/casual remark too seriously,

It was mostly a joke.

> what are you concerned might break?

Any automation that is taken for granted that it works. Maybe some scripts won't take the redirection kindly, who knows... I won't be surprised if we end up being surprised ;) 

I think this change is important for Scala, so it will be worth it nonetheless, even if there are problems.

**Comment by hamzaremmal** [comment]
Hi everyone,
As announced yesterday,  we will start transferring the lampepfl/dotty repository right now. The CI will not be operational for a short time. After the transfer, we will conduct some tests to make sure that everything is working fine and for that, I’ll need to have all the runners available at my disposition. If a job is submitted during that time, I’ll cancel it.
We will keep you all updated at the end of the operation.
Thank you for your understanding.

**Comment by sjrd** [comment]
**It’s done!** You can now all resume submitting PRs and pushing to branches. We recommend that you rebase existing PRs on top of the latest main if you push something new.
