### ISSUE TITLE
Deprecated inline method does not generate deprecation warning

### ISSUE THREAD

**Issue by 2m** [scala/scala3#19913]
## Compiler version

`3.4.0`, `3.4.1-RC1`, `3.3.3`.
## Minimized code

Two deprecated methods, one `inline`.

```scala
//> using scala 3.4.0
//> using option -deprecation

object Deprecated:

  @deprecated("test")
  def method() = ???

  @deprecated("test")
  inline def inlineMethod() = ???

object Test:
  Deprecated.method()
  Deprecated.inlineMethod()
```

## Output

Deprecation warning is not shown for the `inline` method.

```scala
[warn] ./depr.sc:13:3
[warn] method method in object Deprecated is deprecated: test
[warn]   Deprecated.method()
[warn]
```

## Expectation

Both deprecated methods generate deprecation warnings. This was noticed in https://github.com/Iltotore/iron/issues/229

**Comment by som-snytt** [comment]
fwiw this was too much machinery:

https://github.com/scala/scala3/pull/16037

The suggestion there was to move CrossVersionChecks earlier. Unused check runs after typer.

Or maybe original is available to CrossVersionChecks via "inlined body retainer"; I don't remember how that works.

**Comment by nicolasstucki** [comment]
Moving CrossVersionChecks earlier would not help with transparent inline defs. We probably need to check those just before we inline the calls.
