### ISSUE TITLE
Class constructor parameter undercompilation

### ISSUE THREAD

**Issue by sake92** [scala/scala3#19910]
## Compiler version

3.3.1

## Minimized code

```scala
// Hello.scala
object Hello extends App {
  val service = MyService("fssdfs")
  println("Works!")
}

// MyService.scala
class MyService(str: String)
```
compiles and runs fine.

But when you add a parameter to `MyService` constructor, it *still compiles* but fails at runtime with `NoSuchMethodError`.

## Output

```scala
Exception in thread "main" java.lang.NoSuchMethodError: 'void example.MyService.<init>(java.lang.String)'
        at example.Hello$.<clinit>(Hello.scala:5)
        at example.Hello.main(Hello.scala)
```

## Expectation

Code fails to compile.

**Comment by sake92** [comment]
Relevant issues:
https://github.com/sbt/zinc/issues/1334
https://github.com/scalameta/metals/issues/6112

Repro repo:
https://github.com/sake92/metals-mill-scala3-class-params-repro

**Comment by eed3si9n** [comment]
Likely the relevant code is around here where Scala 3 compiler builds up the dependency graph: https://github.com/scala/scala3/blob/a9bb881f13d032219f695d9b7c3fd5ed5c30f059/compiler/src/dotty/tools/dotc/sbt/ExtractDependencies.scala#L172-L211

And here's how you can see the AST after parser phase:

```scala
$ mkdir /tmp/hello
$ scalac scalaHelloWorld/src/main/scala/example/*.scala -d /tmp/hello -Xprint:parser -Yplain-printer
[[syntax trees at end of                    parser]] // scalaHelloWorld/src/main/scala/example/Hello.scala
PackageDef(Ident(example), List(
  ModuleDef(Hello,
    Template(DefDef(<init>, List(), TypeTree(), Thicket(List())),
      List(Ident(App)), ValDef(_, Thicket(List()), Thicket(List())), List(
      ValDef(service, TypeTree(),
        Apply(Select(New(Ident(MyService)), <init>), List(Literal("fssdfs")))),
      Apply(Ident(println), List(Literal("Works!")))))
  )
))

[[syntax trees at end of                    parser]] // scalaHelloWorld/src/main/scala/example/MyService.scala
PackageDef(Ident(example), List(
  TypeDef(MyService,
    Template(
      DefDef(<init>, List(List(ValDef(str, Ident(String), Thicket(List())))),
        TypeTree(), Thicket(List())),
    List(), ValDef(_, Thicket(List()), Thicket(List())), List())
  )
))
```

In particular `Apply(Select(New(Ident(MyService)), <init>), List(Literal("fssdfs"))))`.

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/scala/scala3/pull/19911

**Comment by bishabosha** [comment]
Thank you @sake92 for reporting and @eed3si9n for the investigation and PR!
