### ISSUE TITLE
Crash when refining a private type member

### ISSUE THREAD

**Issue by EugeneFlesselle** [scala/scala3#19929]
## Compiler version

3.4.2-RC1

## Minimized code

```Scala 3
trait A:
  private type M

def foo(a: A{type M = Int}) =
  val _: a.M = ??? // crash
```

Note that replacing `???` with `0` gives an error instead.

## Output (click arrow to expand)

<details>

```scala
  exception while retyping val _$1: a.M = ??? of class ValDef # -1

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Yno-enrich-error-messages.

     while compiling: tests/playground/example.scala
        during phase: MegaPhase{elimErasedValueType, pureStats, vcElideAllocations, etaReduce, arrayApply, elimPolyFunction, tailrec, completeJavaEnums, mixin, lazyVals, memoize, nonLocalReturns, capturedVars}
                mode: Mode(ImplicitsEnabled)
     library version: version 2.13.12
    compiler version: version 3.4.2-RC1-bin-SNAPSHOT-nonbootstrapped-git-3694d95
            settings: -classpath /Users/eugeneflesselle/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.12/scala-library-2.13.12.jar:/Users/eugeneflesselle/Documents/dotty/library/../out/bootstrap/scala3-library-bootstrapped/scala-3.4.2-RC1-bin-SNAPSHOT-nonbootstrapped/scala3-library_3-3.4.2-RC1-bin-SNAPSHOT.jar -d /
cannot resolve reference to type (a : A{type M = Int}).M
the classfile defining the type might be missing from the classpath
```
</details>

**Comment by Gedochao** [comment]
@odersky is this fixed in 7d0d088? can we close it?

**Comment by odersky** [comment]
The fixing commit has been merged since. I think it was on another PR.

**Comment by EugeneFlesselle** [comment]
> The fixing commit has been merged since. I think it was on another PR.

The issue was fixed in #19983, but I do not think it included your [commit](https://github.com/dotty-staging/dotty/commit/7d0d088d04c8c3e7370a9889a6712ff46ce14060). Should I just add a regression test or should those changes be merged ?

**Comment by EugeneFlesselle** [comment]
The test case no longer crashes and does not give an error either. 
I expected it to mean we are refining the trait A with an unrelated public type member M, which would be ok, even if non-obvious. But that does seem to be the case.

```scala 3
```

**Comment by smarter** [comment]
> I expected it to mean we are refining the trait A with an unrelated public type member M, which would be ok, even if non-obvious.

Yes, that would be consistent with how a public def in a subclass can have the same name as a private def, otherwise adding a private definition could break backward compatibility.

**Comment by EugeneFlesselle** [comment]
> Yes, that would be consistent with how a public def in a subclass can have the same name as a private def, otherwise adding a private definition could break backward compatibility.

So it should _not_ compile right ?
