### ISSUE TITLE
Unsound conformance from selection of member MatchType

### ISSUE THREAD

**Issue by EugeneFlesselle** [scala/scala3#19949]
Match type with no cases reduces to unreported `ErrorType`

## Compiler version

3.4.2-RC1

## Minimized code

```Scala
trait T[N]:
  type M = N match
    case 0 => Any // or anything else

val t: T[Double] = new T[Double] {}
val x: t.M = "hello"
val y: Boolean = x // compiles + ClassCastException
```

We also have the same issue when using a projection:
```scala 3
val z: T[Double]#M = "hello"
val _: Boolean = z // compiles + ClassCastException
```

Minimised from @Gedochao's https://github.com/scala/scala3/issues/19936#issuecomment-1997215624

**Comment by Gedochao** [comment]
Doesn't compile on 3.3.3, so it's also a regression...

**Comment by EugeneFlesselle** [comment]
> Doesn't compile on 3.3.3, so it's also a regression...

It was introduced by #18016

**Comment by dwijnand** [comment]
> Doesn't compile on 3.3.3, so it's also a regression...

It looks like it shouldn't compile.  So not a regression, "just" a soundness bug.

**Comment by EugeneFlesselle** [comment]
@sjrd @dwijnand @odersky There are 3 possible solutions:
1. Handling the case in `TypeComparer`
2. Reverting to throwing a `TypeError`
3. Reverting to returning `NoType`

##  Handling the case in `TypeComparer` #19961

This patch is the simplest option but there are probably other cases we are not aware of which don't handle these `ErrorType`s correctly either.

A quick test trying to detect them by adding check in subtype test:
```scala 3
case tp2: FlexType =>  
  tp2 match  
    case errTp: ErrorType if  
      tp2.show.contains("<error The match type contains an illegal case") ||  
      tp2.show.contains("<error Match type reduction failed since selector") => false  
    case _ => true
```
causes several test cases to fail. I haven't investigated further yet but it looks a bit suspicious.

## Reverting to throwing a `TypeError` #19953

This option still has a failure in [`pos/constvalue-of-failed-match-type.scala`](https://github.com/scala/scala3/blob/9ef24bf463c68d0be096ea81e84fda4c5088b1d5/tests/pos/constvalue-of-failed-match-type.scala). The test case specifically wants to allow match types with no matching cases when they are the result of an inlineCall but will be eliminated by further inlining (e.g. in a branch of an inline match from an inline def).

I haven't figure out yet how to catch/handle the error in the `InliningTreeMap`, but I expect it should be possible.

## Reverting to returning `NoType` #19954

The last option is leaving match types with no matching cases unreduced without reporting a type error.

The alternative seems inconsistent with the other kinds of unreducible match types which are simply left as is.
I also understand why an error might be desirable (e.g see [`neg/12974.scala`](https://github.com/scala/scala3/blob/9ef24bf463c68d0be096ea81e84fda4c5088b1d5/tests/neg/12974.scala)) but as the previous example shows it isn't always preferable either.

https://github.com/scala/scala3/issues/19954#issuecomment-2002065944 might also be interesting to look at.

---

In any of the options, we should make sure to keep `MatchTypeLegacyPattern` consistent with `MatchTypeNoCases`.

**Comment by odersky** [comment]
Logically, a match type with no matching cases should simply not reduce (or return NoType, and then upstream we'd not reduce when we see that). When that causes follow-on erorrs (e.g. TypeMismatch) we show the failing reduction in ShowMatchTrace.

**Comment by EugeneFlesselle** [comment]
> Logically, a match type with no matching cases should simply not reduce (or return NoType, and then upstream we'd not reduce when we see that). When that causes follow-on erorrs (e.g. TypeMismatch) we show the failing reduction in ShowMatchTrace.

Okay, that is exactly what #19954 implements. @sjrd mentioned this requiring a SIP https://github.com/scala/scala3/pull/19954#issuecomment-1999938340. If so, should I merge it with covariance improvements ?

**Comment by dwijnand** [comment]
> There are 3 possible solutions:
> 
> 1. Handling the case in `TypeComparer`
> 2. Reverting to throwing a `TypeError`
> 3. Reverting to returning `NoType`

My preference is 1 over 3 over 2, fwiw.
