### ISSUE TITLE
Enum completions in `new` context should be filtered

### ISSUE THREAD

**Issue by rochala** [scala/scala3#19968]
## Compiler version
3.4.1
## Minimized code

```Scala
enum NewEnum:
  case Left, Right

new NewEn@@
new NewEnum.Le@@
```
## Output
Both completions requests suggest `NewEnum` and allow us to compile it even if they are illegal and will result in error.
## Expectation

These completions should be hidden as they are illegal in this context.

**Comment by mbovel** [comment]
This issue was picked for the Scala Issue Spree of April 30th. @mbovel and @aherlihy will be working on it. If you have any insight into the issue or guidance on how to fix it, please leave it here.

**Comment by mbovel** [comment]
Spree team update: @rochala and @aherlihy will work on this tomorrow, via Zoom.
