### ISSUE TITLE
Wrong 'Cannot be checked at runtime' warning for union types

### ISSUE THREAD

**Issue by scf37** [scala/scala3#19977]
## Compiler version

3.4.0

## Minimized code

```Scala
trait Foo

def foo(v: Int | Seq[String]): Unit = v match
  case s: Int => 
  case s: Seq[String] => // ok for Int

def foo2(v: Foo | Seq[String]): Unit = v match
  case s: Foo => 
  case s: Seq[String] => // cannot be checked warning for Foo
```

## Output

```scala
the type test for Seq[String] cannot be checked at runtime because its type arguments can't be determined from Playground.Foo
```

## Expectation
No warning because input union type specifies type argument explicitly.

**Comment by odersky** [comment]
There could be a subclass that implements `Foo` and `Seq[T]` for `T` different from `String`. So the warning is correct.

In the case of `Int` we don't emit a warning since `Int` is final.
