### ISSUE TITLE
nowarn falsely reports "annotation does not suppress any warnings" when suppressing unused private members

### ISSUE THREAD

**Issue by felher** [scala/scala3#19992]
## Compiler version

3.3.3

## Minimized code

```Scala
@scala.annotation.nowarn()
object Test:
  private val aa = "aa"
```

Scastie at https://scastie.scala-lang.org/OVJH4ESRR4iswVLoeyay2A

## Output

```
@nowarn annotation does not suppress any warnings
```

## Expectation

Should not output a warning since it suppresses a "unused private member" warning that would appear otherwise.

## Similar to

Maybe a duplicate of #18341 ?

**Comment by Gedochao** [comment]
> Maybe a duplicate of https://github.com/scala/scala3/issues/18341 ?

Seems to be the case.
I'm closing this, let's track it under #18341
