### ISSUE TITLE
Wrong rewrite of a partial function passed to a symbolic operator

### ISSUE THREAD

**Issue by OndrejSpanel** [scala/scala3#20002]
## Compiler version

3..4.1-RC2

## Minimized code

Use `-indent -rewrite` on following code:

```Scala
@main
def main: Unit = {

  object reactions {
    def += (f: PartialFunction[String, Unit]) = ???
  }

  reactions += {
    case a =>
    case b =>
  }
}
```

## Output

```scala
@main
def main: Unit =

  object reactions:
    def += (f: PartialFunction[String, Unit]) = ???

  reactions += :
    case a =>
    case b =>
```

Compiling this results in following error:

> C:\Dev\Sandbox\src\main\scala\Main.scala:7:16
> expression expected but : found
>   reactions += :

## Expectation

The output of "-indent", "-rewrite" should compile without errors

## Note

This pattern is common when using Scala Swing.

**Comment by OndrejSpanel** [comment]
A similar pattern is also often seen in parser / combinators, where partial function follows `^^`.

**Comment by LucySMartin** [comment]
I'm having a look at this. No promises, very new to this stuff, but I've reproduced and found a good looking spot to try some changes.

**Comment by LucySMartin** [comment]
I've raised #20043 - I think it fixes this
