### ISSUE TITLE
Tailrec optimisation and export

### ISSUE THREAD

**Issue by sned65** [scala/scala3#20011]
## Compiler version

3.4.0

## Minimized code

```Scala
class A {
  val m = new scala.collection.concurrent.TrieMap[Int, Int]()
  export m.clear
}
```

## Output

The compilation error: "TailRec optimisation not applicable, method clear contains no recursive calls".

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/scala3/issues/19505 which is fixed on 3.4.1.
