### ISSUE TITLE
Given leaked in outer scope

### ISSUE THREAD

**Issue by nicolasstucki** [scala/scala3#20071]
## Compiler version

3.5.0-RC1-bin-SNAPSHOT

## Minimized code

```Scala
trait Decoder
object Decoder:
  given foo: Int = ???

type DecoderToInt[Why] >: Int <: Int

def bar[T](using d: DecoderToInt[T]): Any = ???
def test: Unit = bar[Decoder]

```

## Output

Compiles (but should not)

## Expectation

Should not compile. `foo` should not be available in `test` witouth an import.

**Comment by nicolasstucki** [comment]
This is a minimization from `tests/pos/i15183` when compiling the two files at the same time.

**Comment by odersky** [comment]
`Bar[Decoder]` has type 

    (using d: DecoderToInt[Decoder]): Any

`Decoder` appears in that type, so it is in the implicit scope.

I think the issue has rather to do with match types. Sometimes they are resolved sometimes not, and the implicit scope is different for the two versions.

**Comment by odersky** [comment]
I can confirm, that's excactly what happens. `decoder` and `test` are run together, `M[Decoder]` is simplified to `Int`, so `Decoder` does not reduce to the implicit scope. But if we compile `test_2` separately, we still see an `M[Decoder]`.

**Comment by odersky** [comment]
Not sure what to do about this second example.

**Comment by EugeneFlesselle** [comment]
> Not sure what to do about this second example.

Yes indeed, contrarily to the implicit scope situation where consistently making both case fail was good enough. 
The same canot be said here, doing `compareAppliedType`s only on normalised types not only makes the TypeComparer much slower, but also breaks many use cases relying on the inference of match type scrutinees.

This also might related to #18261
