### ISSUE TITLE
Scala3 `-language` compiler option issues

### ISSUE THREAD

**Issue by satorg** [scala/scala3#20083]
First discussed on [Scala Contributors](https://contributors.scala-lang.org/t/scala3-language-compiler-option-issues/6617)

## Compiler version

All Scala3 versions v3.0.0 through v3.4.1

## Minimized code

The `-language` compiler option does not behave as expected:

1. `-language:help` does not provide available choices:
    ```
    % scala-cli compile -S 3.4.1 -O -language:help -- empty.scala  
    ```
    (no available choices returned)

2. `-language` with an incorrect choice does not fail compilation:
    ```
    % scala-cli compile -S 3.4.1 -O -language:WRONG -- empty.scala
    ```
    (no errors reported, the file compiles successfully)

## Expectation

The behavior should look similar to Scala2 compilers, e.g.:
```
% scala-cli compile -S 2.13.13 -O -language:help -- empty.scala                       
Enable or disable language features
  dynamics             Allow direct or indirect subclasses of scala.Dynamic
  existentials         Existential types (besides wildcard types) can be written and inferred
  higherKinds          Allow higher-kinded types
  implicitConversions  Allow definition of implicit functions called views
  postfixOps           Allow postfix operator notation, such as `1 to 10 toList` (not recommended)
  reflectiveCalls      Allow reflective access to members of structural types
  experimental.macros  Allow macro definition (besides implementation and application)

% scala-cli compile -S 2.13.13 -O -language:WRONG -- empty.scala
scalac error: 'WRONG' is not a valid choice for '-language'
  scalac -help  gives more information
Compilation failed
```

**Comment by som-snytt** [comment]
Especially as there is no `-language:all` equivalent to `-language:_`, which is what you reach for when doing a quick test and can't be bothered with spelling it out. There is no indicator at all.

No doubt, when the dust settles around other important features and people begin to miss `-language:_`, there will be a general mutiny.

An alternative would be a `-language:test` environment that relaxes all sorts of restrictions but just for testing. I can't think of one, but could imagine "empty package" available only under this `test` regime, or empty packages from arbitrary sources (directories or binary artifacts).
