### ISSUE TITLE
Implement Scala CLI as the `scala` runner command

### ISSUE THREAD

**Issue by Gedochao** [scala/scala3#20098]
**Corresponding Scala CLI issue**
- https://github.com/VirtusLab/scala-cli/issues/2838

**Relevant docs**
- [SIP-46 details](https://github.com/scala/improvement-proposals/blob/main/content/scala-cli.md)
- [experimental Scala CLI as scala installation](https://scala-cli.virtuslab.org/docs/reference/scala-command/#testing-scala-cli-as-scala)
- [migration from the old Scala runner (a guide)](https://scala-cli.virtuslab.org/docs/reference/scala-command/#migrating-from-the-old-scala-runner-to-scala-cli)

**Requirements**
- [x] set up downloading of Scala CLI JVM launcher from GitHub VirtusLab/scala-cli
- [x] download library dependencies to the dist/target/pack in maven repo style
- [x] fix scripts to wrap  Scala CLI launcher, setting both the local repo and default scala version launcher options
  - [x] update for windows (batch)
  - [x] update for linux/mac (bash)
- [ ] run any existing legacy (old) `scala` runner tests against the Scala CLI launcher on the `scala/scala3` CI
- [ ] use the Scala CLI launcher instead of the `scala` runner in official Scala 3 distributions
  - [x] coursier
  - [ ] brew
  - [ ] SDKMAN

**Comment by bishabosha** [comment]
the strategy of downloading the launcher looks like it can't handle script files compiled with a higher tasty version than scala-cli itself:
```
$ echo 'println(23)' >> local/foo.sc
$ scala-cli --cli-default-scala-version 3.5.0-RC1-bin-SNAPSHOT -r file://dist/target/pack/maven2  local/foo.sc --server=false
Scala CLI (v1.3.0) cannot post process TASTY files from Scala 3.5.0-RC1-bin-SNAPSHOT.
This is not a fatal error since post processing only cleans up source paths in TASTY file.
It should not affect your application.
You may be getting this warning because you are using a newer version of Scala than the one supported by Scala CLI (v1.3.0).
Make sure your Scala CLI is up-to-date.
You may need to wait for 3.5.0-RC1-bin-SNAPSHOT support in a future version of Scala CLI.

23
```
