### ISSUE TITLE
Spourious unused renamed import warning

### ISSUE THREAD

**Issue by nicolasstucki** [scala/scala3#20146]
## Compiler version

3.3.3, 3.4.0, 

## Minimized code

```Scala
//> using options -Wunused:all

def test(list: List[Int]): Int =
  import list.{head => first}
  first
```

## Output

```scala
4 |  import list.{head => first}
  |               ^^^^^^^^^^^^^
  |               unused import
```

## Expectation
Should not warn

**Comment by noti0na1** [comment]
When importing a term and renaming it, we will translate the usage of the renamed term into the original selection in typer.

In this case, `first` becomes `list.head`; hence, the import checker couldn't find the usage of `first`.
