### ISSUE TITLE
Upper bound with refinement defaults to `Object` and not to `Any`

### ISSUE THREAD

**Issue by pweisenburger** [scala/scala3#20240]
The following code compiles:

```scala
trait A:
  type T

trait B extends A:
  type U
  type T <: U
```

But after changing the definition of  of `A` to:

```scala
trait A:
  type T <: { }
```

The code fails with:

```
error overriding type T in trait A with bounds <: Object;
  type T with bounds <: B.this.U has incompatible type
```

It can be made compile with the following:

```scala
trait A:
  type T <: Any { }
```

This is not really a bug, but it is somewhat surprising that a refinement changes the upper bound from `Any` to `Object`. It means that a solution is to write down the `Any` upper bound explicitly on every refinement. It seems a little bit inconsistent with the default upper bound being `<: Any` in other cases (and not `<: Object`). I noticed that a single line could be changed to make the default "parent" of a refinement `Any` instead of `Object`:

```diff
--- a/compiler/src/dotty/tools/dotc/typer/Typer.scala
+++ b/compiler/src/dotty/tools/dotc/typer/Typer.scala
@@ -2209,7 +2209,7 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
   }
 
   def typedRefinedTypeTree(tree: untpd.RefinedTypeTree)(using Context): TypTree = {
-    val tpt1 = if (tree.tpt.isEmpty) TypeTree(defn.ObjectType) else typedAheadType(tree.tpt)
+    val tpt1 = if (tree.tpt.isEmpty) TypeTree(defn.AnyType) else typedAheadType(tree.tpt)
     val refineClsDef = desugar.refinedTypeToClass(tpt1, tree.refinements).withSpan(tree.span)
     val refineCls = createSymbol(refineClsDef).asClass
     val TypeDef(_, impl: Template) = typed(refineClsDef): @unchecked
```

My question is: Is there an inherent reason why the default is `Object` instead of `Any` or is there a chance a pull request would be accepted to change the default?

**Comment by sjrd** [comment]
This behavior is as specified. I think I failed to carry over the spec text from 2.13 to 3.4, but in the Scala 2.13 specification you can clearly find:
https://scala-lang.org/files/archive/spec/2.13/03-types.html#compound-types

> A compound type may also consist of just a refinement `{R}` with no preceding component types. Such a type is equivalent to `AnyRef {R}`.

Changing it would be a breaking change requiring a SIP, and I don't think it is likely to be accepted.
