### ISSUE TITLE
Inferred type of scala.quoted.Type for opaque type differs when fully qualified

### ISSUE THREAD

**Issue by tschuchortdev** [scala/scala3#20303]
## Compiler version

3.3.3

## Minimized code

```Scala
// file Main.scala
package com.foo

class A
opaque type Opaque = A

inline def myMacro = ${ myMacroImpl }

def myMacroImpl(using q: Quotes) = {
  import q.reflect.*

  val t0 = summon[Type[A]] // inferred type: Type[A]
  val t1 = summon[Type[Opaque]] // inferred type: Type[A]
  val t2 = summon[Type[com.foo.Main$package.Opaque]] // inferred type: Type[Opaque]
  '{ () }
}
```

## Expectation

I would expect t1 and t2 to have the same inferred type, either both `A` or both `Opaque`. Since `Opaque` is transparent in this scope, I suppose it is not incorrect to infer `A`, however, I think that inferring `Opaque` is much more useful in macros: We can easily go from a type alias to the RHS, but not the other way around.

Perhaps this is the intended behaviour, but it was certainly surprising to me.

**Comment by odersky** [comment]
That's actually as expected. `t2` sees the type of `Opaque` as seen from outside the package.
