### ISSUE TITLE
False-positive globally reachable private Java vars under `-Ycheck-reentrant`

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#20324]
## Compiler version
3.5.0-RC1-bin-20240501-e6bc130-NIGHTLY 

## Minimized example
Found in Scala 2 compiler forward-port https://github.com/scala/scala3/pull/19897

```Scala
private val Close = java.nio.CharBuffer.allocate(0)
```

## Output

```scala
> scala-cli compile --server=false sandbox.scala -S 3.nightly -Ycheck-reentrant -Ylog:checkReentrant+ 
possible data race involving globally reachable variable isReadOnly in class CharBuffer: Boolean
  use -Ylog:checkReentrant+ to find out more about why the variable is reachable.
possible data race involving globally reachable variable address in class Buffer: Long
  use -Ylog:checkReentrant+ to find out more about why the variable is reachable.
2 errors found
Compilation failed
```

## Expectation
`isReadOnly` and `address` are private/package private? variable, first of them can be only accessed via the accessor method. These should not be reported.

**Comment by bishabosha** [comment]
my thought was that it doesn't care about private because all that matters is "is there a mutable field" and so someone could call something public that changes the field

**Comment by WojciechMazur** [comment]
Maybe, that would also make sense. I don't know the scope of `-Ycheck-reentrant` flag and neither understand it yet, so I'm leaving it to decide how it should be handled.

**Comment by Gedochao** [comment]
@odersky thoughts on this behaviour?

**Comment by odersky** [comment]
I think that's a reasonable warning. The fix is to annotate `Close` with @sharable.
