### ISSUE TITLE
Opaque type defined in object cannot be compared to null

### ISSUE THREAD

**Issue by OndrejSpanel** [scala/scala3#20331]
## Compiler version

3.0.0 - 3.4.1

## Minimized code

```scala
object Outer:
  opaque type Inner = AnyRef

  object Inner:
    def apply(): Inner = new {}

opaque type Plain = AnyRef

object Plain:
  def apply(): Plain = new {}

@main
def main(): Unit = {
  println(Outer.Inner() == null)
  println(Plain() == null)
}

```

## Output

Error:

> Values of types Outer.Inner and Null cannot be compared with == or !=

## Expectation

It should be possible to compare instances of `Inner` to `null`.

## Note

Comparison with `null` works fine for `Plain`.

One might attempt to use following workaround:

```
  def isNull(any: AnyRef): Boolean = any == null
  println(isNull(Outer.Inner()))
```

This gives a different error, which is also confusing (where is an implicit conversion?):

> the result of an implicit conversion must be more specific than AnyRef

## Workaround

Using `Any` instead of `AnyRef` works:

```
  def isNull(any: Any): Boolean = any == null
  println(isNull(Outer.Inner()))
```

**Comment by som-snytt** [comment]
https://dotty.epfl.ch/docs/reference/other-new-features/opaques-details.html#top-level-opaque-types-1

> This behavior becomes clear if one recalls that top-level definitions are placed in their own synthetic object.

The message note, as noted:
```
   |                 Note that implicit conversions were not tried because the result of an implicit conversion
   |                 must be more specific than AnyRef
```
does not imply that there is an available conversion. Arguably, it "heads off" the exploratory programmer "at the pass" before trying to add such a conversion.

**Comment by OndrejSpanel** [comment]
I see now.

If I want `Inner` to be tested against `null` I should write:

> opaque type Inner >: Null = AnyRef

There is no issue, closing.
