### ISSUE TITLE
Publish Scala 3 alongside Scala CLI as the scala runner on Scoop

### ISSUE THREAD

**Issue by Gedochao** [scala/scala3#20386]
https://scoop.sh/

**Comment by hamzaremmal** [comment]
Scoop already has a `scala` manifest and they have some automation to update it. 
I've updated the links from `lampepfl/dotty` to `scala/scala3` and will adapt the manifest to the changes in 3.5.0. 
Otherwise, I will consider this issue as closed.

**Comment by hamzaremmal** [comment]
Actually, the licence will need to be updated too...
