### ISSUE TITLE
Publish Scala 3 alongside Scala CLI as the scala runner on winget

### ISSUE THREAD

**Issue by Gedochao** [scala/scala3#20381]
https://learn.microsoft.com/en-us/windows/package-manager/winget/

Example from Scala CLI repo:
https://github.com/VirtusLab/scala-cli/blob/main/.github/workflows/ci.yml#L1679-L1684

**Comment by Gedochao** [comment]
Note: if we end up using the [winget-releaser](https://github.com/vedantmgoyal9/winget-releaser) GitHub action, make sure to use it on `@main` rather than `v2`.
Context:
- https://github.com/VirtusLab/scala-cli/pull/2991
- https://github.com/VirtusLab/scala-cli/issues/2689
- https://github.com/vedantmgoyal9/winget-releaser/issues/287

**Comment by hamzaremmal** [comment]
I'm not a big fan of using `@main` tbh

**Comment by hamzaremmal** [comment]
Yea, since that PR is opened by the owner of the repository, I asked in https://github.com/VirtusLab/scala-cli/pull/2991#issuecomment-2205894343

**Comment by bishabosha** [comment]
you can also do `@commit`?

**Comment by hamzaremmal** [comment]
Yes we can always do that (which is my backup plan if no release with this changes is done)
I'd rather have a release since @dependabot can suggest to update the dependency.
