### ISSUE TITLE
Publish Scala 3 alongside Scala CLI as the `scala` runner on Chocolatey

### ISSUE THREAD

**Issue by Gedochao** [scala/scala3#20380]
https://chocolatey.org/

An example implementation, as done in the Scala CLI repository:
https://github.com/VirtusLab/scala-cli/blob/main/.github/workflows/ci.yml#L1675-L1678

**Comment by hamzaremmal** [comment]
A [profile](https://community.chocolatey.org/profiles/scala) for `scala` is already created !
