### ISSUE TITLE
Unknown `-language` option yields an error

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#20419]
Before 3.5 passing `-language:higherKinds` was simply ignored without any mesage, now, it's yielding a compilation error. This conflicts with handling of other unknown scalac options, which emit warnings. 
The new behaviour is problematic when project use utilities to set common `scalacOptions` like https://github.com/typelevel/sbt-tpolecat - it requires to modify the upstream project and release it or to introduce a special exclusion rules in the build. 

## Compiler version
Last good release: 3.5.0-RC1-bin-20240512-99c4c00-NIGHTLY
First bad release: 3.5.0-RC1-bin-20240514-7c9aae3-NIGHTLY
Bisect points to: f6345c6202b69a4603cb61ca029d60aa2ac80599

## Minimized code

```Scala
//> using options -language:higherKinds

@main def Test = ()
```

## Output

```scala
[error] invalid choice(s) for -language: higherKinds
[info]   scalac -help  gives more information
```

## Expectation
Unknown variant of option should yield warning instead of error.

**Comment by noti0na1** [comment]
`-language` is a choice flag now, so it errors out any invalid choice like other flags, for example, `-source`.

We should make a decision what behaviour we want for this kind of flags.

**Comment by som-snytt** [comment]
As a warning, `bad option '-junk' was ignored` is not very opinionated. `-Yrangepos` is the one I remember being ignored.

`sbt-tpolecat` is the unproblematic case: its job is to present correct options.

**Comment by WojciechMazur** [comment]
In the last OpenCB there are 434 failures, seems like all of this failures are caused by `-language:higherKinds` or other no longer viable options https://virtuslab.github.io/community-build3/2024/05/18/3.5.0-rc1-bin-20240516-c608177-nightly.html 
We can adapt OpenCB to try filter out the no longer valid options, but still, it seems like large amount of ecosystem was using no-op flag for a long time.

**Comment by Gedochao** [comment]
@noti0na1 
Some notes after core meeting:
- we should accept options from Scala 2, including `-language:higherKinds`.
- for unknown options, it is correct to fail.

**Comment by noti0na1** [comment]
@Gedochao Do we also accept `_` with no effect?

**Comment by Gedochao** [comment]
> @Gedochao Do we also accept `_` with no effect?

@noti0na1 Nice catch.
No, we don't want to accept `_`.
