### ISSUE TITLE
Scala-docs: incorrect link on source file

### ISSUE THREAD

**Issue by dos65** [scala/scala3#20465]
At https://www.scala-lang.org/api/current in any page for class link on source leads to 404 .

For example: https://www.scala-lang.org/api/current/scala/collection/concurrent/Map.html -> Attributes `Source` follows to https://github.com/scala/scala3/blob/3.4.2/out/bootstrap/scala2-library-bootstrapped/scala-3.5.0-RC1-bin-SNAPSHOT-nonbootstrapped/src_managed/main/scala-library-src/scala/collection/concurrent/Map.scala#L40

**Comment by KacperFKorban** [comment]
Essentially duplicate of #20058
