### ISSUE TITLE
Context function can not be returned from transparent inline macro

### ISSUE THREAD

**Issue by rssh** [scala/scala3#20473]
## Compiler version

3.4.2

## Minimized code

file Macro.scala
```Scala
package x

import scala.quoted.*

trait XContext


object Macro {

  transparent inline def retContext[A](inline body: A): Any = ${
     retContextImpl('body)
  }

  def retContextImpl[A:Type](body: Expr[A])(using Quotes): Expr[Any]  = {
     import quotes.reflect.*
     '{ (x: XContext) ?=> ${body} }
  }

}

```

file Main.scala
```Scala
package x

object Main {

  def main(args:Array[String]): Unit = {
     val r = Macro.retContext(1)
     println(r)
  }

}
  
```

## Output

```scala
[info] compiling 1 Scala source to /Users/rssh/tests/dotty/context-function-in-inline/target/scala-3.4.2/classes ...
[info] compiling 1 Scala source to /Users/rssh/tests/dotty/context-function-in-inline/target/scala-3.4.2/classes ...
[error] -- [E172] Type Error: /Users/rssh/tests/dotty/context-function-in-inline/src/main/scala/x/Main.scala:6:32 
[error] 6 |     val r = Macro.retContext(1)
[error]   |                                ^
[error]   |No given instance of type x.XContext was found for parameter of (x.XContext) ?=> Int
[error] one error found

```

## Expectation

should compile

**Comment by odersky** [comment]
Yes, I think that's a known limitation. Context functions are never inferred; they have to be explicitly declared.

**Comment by rssh** [comment]
This should be at least be written in the documentation

**Comment by rssh** [comment]
And the error message is completely cryptic

**Comment by odersky** [comment]
Can you suggest specific wording to improve the documentation? I believe the behavior follows from the principles that are already outlined, namely that every context function type in the result of an expression is immediately and implicitly applied.

**Comment by rssh** [comment]
In https://docs.scala-lang.org/scala3/reference/metaprogramming/inline.html we see:
```
Inline methods can additionally be declared transparent. This means that the return type of the inline method can be specialized to a more precise type upon expansion.
```
  I.e. user expect that return type is specializated,  not inferred.  

One of the possible approaches is to add the next paragraph:
  
If we will attempt to return context function,  than instead specializing return type, compiler will try to infern non-context type, because context functions are never inferred.

Therefore next code:
```
package x

import scala.quoted.*

trait XContext


object Macro {

  transparent inline def retContext[A](inline body: A): Any = ${
     retContextImpl('body)
  }

  def retContextImpl[A:Type](body: Expr[A])(using Quotes): Expr[Any]  = {
     import quotes.reflect.*
     '{ (x:XContext) ?=> $body }
  }

}

```

```
package x

object Main {

  def main(args:Array[String]): Unit = {
     given XContext = new XContext {}
     val r = Macro.retContext(1)
     println(r)
  }

}
```
  will infern type of r as 1,   even if we explicit return context function.

**Comment by rssh** [comment]
I can submit simular path to docs,  if this is an intended behaviour.
