### ISSUE TITLE
Slow inference with large Maps of literals

### ISSUE THREAD

**Issue by adkian-sifive** [scala/scala3#20521]
## Compiler version

3.4.0, 3.4.1, 3.4.2

## Minimized code

I put it in a gist here since the problematic Maps are quite large: [https://gist.github.com/adkian-sifive/5c904054f400871f2fe712ab160be1b3](https://gist.github.com/adkian-sifive/5c904054f400871f2fe712ab160be1b3)

## Output
The compiler hangs

## Expectation
In this case the compiler should complain about not finding a main method, but it does not do that and just hangs.

**Comment by som-snytt** [comment]
3.4.2 takes just over two minutes to compile on my old box. (2.13.14 takes a few seconds. IIRC it checks for all the same primitive when lubbing.)

TIL 2.13 does not try to initialize a main-less object. 3.4 does indeed complain.

**Comment by adkian-sifive** [comment]
Thanks for checking! After retrying with a bit more patience it did indeed complain after around 5 mins on my old potato. Perhaps a performance enhancement opportunity but doesn't seem like a bug...

**Comment by som-snytt** [comment]
For example https://github.com/scala/scala3/issues/19907

That is already in 3.4.2.

On HEAD, the example is still over a minute (trying it locally, informally).

**Comment by jackkoenig** [comment]
Thanks for the additional context!

Do you think this is worth re-filing separately as a performance issue?

**Comment by som-snytt** [comment]
There are a couple of open PRs for performance of calculating intersection types, but I don't know if they will apply here.

It couldn't hurt to reopen this ticket and let normal triage take its course, so I'll do that.

**Comment by noti0na1** [comment]
Actually, after re-running the test, I find the nightly version is 30% faster than the LTS version on my computer. But it is still much slower than Scala 2.

* Scala 2: 9s
* Scala 3.4.2: ~60s
* Scala 3.6.0-RC1-bin-20240717-45dcb51-NIGHTLY: ~40s

**Comment by noti0na1** [comment]
With #21223, the compiling time can be reduced to Scala 2 level.
