### ISSUE TITLE
`compiletime.uninitialized` refuses to compile in local position

### ISSUE THREAD

**Issue by soronpo** [scala/scala3#20537]
## Compiler version

v3.3.3
v3.5.0-RC1

## Minimized code

```scala
object Test:
  locally:
    var x: Int = compiletime.uninitialized //error
```

## Output

```scala
`uninitialized` can only be used as the right hand side of a mutable field definition
```

## Expectation
No error.

**Comment by sjrd** [comment]
Hum, that error looks completely correct to me, and informative too. It tells you exactly what's wrong. You can only use for fields, not for locals.

**Comment by soronpo** [comment]
> Hum, that error looks completely correct to me, and informative too. It tells you exactly what's wrong. You can only use for fields, not for locals.

Oh, I thought locals are fields, as in local fields. Why should this be a limitation?

**Comment by sjrd** [comment]
Because none of our targets accepts an uninitialized local variable. ;) We wouldn't be able to compile it.

**Comment by soronpo** [comment]
OK, thanks for the clarification
