### ISSUE TITLE
odd evaluation order when using extension method named `|` as infix method

### ISSUE THREAD

**Issue by dragove** [scala/scala3#20559]
## Compiler version
3.4.2
If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

## Minimized code

```Scala
extension [A](x: Option[A])
  def |[B](f: A => B): Option[B] = x.map(f)
  def ??[B >: A](r: => B): B = x.getOrElse(r)

val data = Option(0)
  | (_ * 4)
  ?? 14
```

## Output

Missing parameter type

I could not infer the type of the parameter _$1
in expanded function:
  _$1 => _$1 * 4
Expected type for the whole anonymous function:
  ?{ ?? : ? }

## Expectation

No Compile Error

this code should get the same result as following code

```scala
extension [A](x: Option[A])
  def ?[B](f: A => B): Option[B] = x.map(f)
  def ??[B >: A](r: => B): B = x.getOrElse(r)

val data = Option(0)
  ? (_ * 4)
  ?? 14
```

**Comment by som-snytt** [comment]
https://scala-lang.org/files/archive/spec/3.4/06-expressions.html#infix-operations

shows low precedence of vbar.
