### ISSUE TITLE
Stabilise SIP 47 - Clause Interleaving

### ISSUE THREAD

**Issue by bishabosha** [scala/scala3#20769]
referencing comment https://contributors.scala-lang.org/t/when-will-sip47-clauseinterleaving-graduate-beyond-experimental/6686/3 - it is now considered shipped

## Actions

remove `scala.language.experimental.clauseInterleaving` requirement from `3.6`

**Comment by Gedochao** [comment]
This has been decided to be included in the 3.6.0 release.

**Comment by xuwei-k** [comment]
- https://github.com/scala/scala3/discussions/21195 🤔
