### ISSUE TITLE
Unexpected inferred union type with chained expressions

### ISSUE THREAD

**Issue by ACoalzy** [scala/scala3#20948]
## Compiler version

3.3.3 LTS

## Minimized code

```Scala
class EqualOps[T](val t: T) extends AnyVal {
  def ===(u: T): Boolean = t == u
}

EqualOps(0) === "string" // does compile, T inferred to be [Int | String]

val a = EqualOps(0)
a === "string" // doesn't compile
```

## Output

```scala
EqualOps(0) === "string" // T inferred to be [Int | String]
```

## Expectation

Referential transparency to be maintained and to be able to replace `a` with `EqualOps(0)`

**Comment by sjrd** [comment]
As designed.

Referential transparency is only a thing after elaboration (type inference). During elaboration, the local presence of more or less information can change things.

**Comment by jdrphillips** [comment]
Is there any documentation on the migration impact of this from scala 2 to 3? I was unable to find any. It doesn't introduce any bugs but it silently introduces the capacity for bugs in an unknown number of places

**Comment by sjrd** [comment]
https://docs.scala-lang.org/scala3/guides/migration/incompatibility-table.html#type-inference

**Comment by jdrphillips** [comment]
> Some specific type inference rules have changed between Scala 2.13 and Scala 3.

"Here be dragons" 😁

**Comment by ACoalzy** [comment]
Is there anything that can be done to avoid this? Another example below using `Set`. This feels like a very probable situation to have occur and a developer could reasonably expect the compiler to catch this mistake. It feels nonintuitive that the behaviour would differ between the last two lines.

```
val a: Option[Int] = Some(1)
val b: Option[Int] = Some(2)
val c: Option[Int] = None

val set = Set(a, b, c)
set.contains(Some(3))
set.contains(3) // this does not compile as expected
Set(a, b, c).contains(3) // this does compile
```
