### ISSUE TITLE
Type pattern not widening scrutinee type

### ISSUE THREAD

**Issue by EugeneFlesselle** [scala/scala3#20992]
## Compiler version

3.5.1-RC1-bin-SNAPSHOT-nonbootstrapped-git-cd8c5ed

## Minimized code

Minimized from [i7294.scala](https://github.com/scala/scala3/blob/main/tests/neg/i7294.scala) with @hamzaremmal 

```Scala
object Test:

  trait Foo:
    val x: Any

  ??? match
    case f: Foo =>
      (f: Foo).x // ok
      f.x // error
```

## Output

```scala
-- [E007] Type Mismatch Error: tests/playground/example.scala:11:6 -------------
11 |      f.x // error
   |      ^
   |Found:    (f : Nothing)
   |Required: ?{ x: ? }
   |Note that implicit conversions were not tried because the result of an implicit conversion
   |must be more specific than ?{ x: <?> }
```

## Expectation

no error

**Comment by EugeneFlesselle** [comment]
Actually not sure this is an error since the following is accepted:
```scala
(??? : Option[Int]) match
    case a: Any => a.get
```

**Comment by hamzaremmal** [comment]
Note that this is the behavior under the `-source 3.6`

**Comment by odersky** [comment]
It's because ??? has type Nothing, so the pattern has type Nothing as well. We use what we know from the scrutinee and from the pattern to type the pattern, so this looks as expected.

**Comment by dwijnand** [comment]
I agree.
