### ISSUE TITLE
Enable all Presentation Compiler tests on the CI for PRs (including Windows tests)

### ISSUE THREAD

**Issue by Gedochao** [scala/scala3#20991]
## Current behaviour

PRs affecting the Presentation Compiler require the `[test_windows_full]` tag , which is easy to forget about, and launches suites which aren't necessary.

## Expectation

PR's affecting the presentation compiler should also trigger a new job on windows that runs `scala3-presentation-compiler-bootstrap/test` and `scala3-language-server/test` when changes are made in modules mentioned above.

**Comment by Gedochao** [comment]
FYI cc @hamzaremmal

**Comment by tgodzik** [comment]
The presentation compiler tests only broke the CI because the default tests are run on JDK 17, only the windows ones are run on JDK 8. Why is that? What is the purpose of using JDK 1, which doesn't really verify if we can compile using JDK 8?

**Comment by tgodzik** [comment]
Should I:

1. windows and JDK 8 job for presentation compiler only
2. separate JDK 8 and windows jobs for presentation compiler
3. switch the defaults to use JDK 8 on PRs
