### ISSUE TITLE
New classpath management system in launchers might break

### ISSUE THREAD

**Issue by hamzaremmal** [scala/scala3#21034]
## Compiler version

main (https://github.com/scala/scala3/commit/f2829c3fab28cc6ab47a5627abda855884476572)

## Issue example

https://github.com/scala/scala3/pull/20631 changes the management of the classpath for the `scaladoc.bat` and `scalac.bat` commands. With this new structure, the length of the classpath is now much bigger than what is was previously and even reaching some of the limits set by windows : https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation

Discovered while debugging an workflow run in https://github.com/scala/scala3/pull/20547

## Expectation

We should reduce the length of the classpath variable to have enough margin to append other options and to avoid malfunctions

**Comment by bishabosha** [comment]
the technique is ultimately the same as before, just the number of entries grew in scaladocs classpath

**Comment by hamzaremmal** [comment]
Yes, this issue tackles the fact that now we have `/maven2/.../file.jar` instead of `/lib/file.jar`, therefore increasing the number of characters and reaching the limit set by Windows
