### ISSUE TITLE
Indentation-based syntax does not tolerate partial function values.

### ISSUE THREAD

**Issue by megri** [scala/scala3#21135]
## Compiler version

3.3.3+

## Minimized code

```scala
def f(pf: PartialFunction[Int, Int]): Option[Int] = pf.lift.apply(1)

f:
  case 1 => 2
  case 2 => 4
```

Scastie: https://scastie.scala-lang.org/VUjTRHzvSkGvsvhZu1cpFQ

## Output

```
error: indented definitions expected, case found
```

followed by
```
'}' expected, but 'case' found
Not found: $t
```

## Expectation

I'd expect it to work like

```scala
def f(pf: PartialFunction[Int, Int]): Option[Int] = pf.lift.apply(1)

f {
  case 1 => 2
  case 2 => 4
}
```

**Comment by tgodzik** [comment]
Thanks for reporting! This actually looks like an issue in [scalameta](https://github.com/scalameta/scalameta) <- could you open an issue there. I see the code actually compiles using scala-cli

**Comment by Gedochao** [comment]
As mentioned, this isn't a problem with the Scala compiler per se, should be raised and tracked upstream.
Closing this issue, as there doesn't seem anything to be done on our side. The code compiles correctly.
