### ISSUE TITLE
Under experimental.modularity, cannot extend a class inheriting a deferred given

### ISSUE THREAD

**Issue by rjolly** [scala/scala3#21189]
## Compiler version

3.5.0-RC3 with -source:future -language:experimental.modularity

## Minimized code

```Scala
trait Ord[T]

trait Sorted[T]:
  given Ord[T] as ord = compiletime.deferred

class SortedSet[T : Ord] extends Sorted[T]

class SortedSet2[T : Ord] extends SortedSet[T]
```

## Output

```scala
^
error overriding given instance ord in class SortedSet of type Ord[T];
  given instance ord of type Ord[T] cannot override final member given instance ord in class SortedSet
```

## Workaround

```Scala
class SortedSet[T : Ord] extends Sorted[T]:
  override given ord: Ord[T] = summon
```

**Comment by rjolly** [comment]
Never mind. Written as below it works:
```Scala
trait Sorted[T : Ord]
```

**Comment by bishabosha** [comment]
I can't reproduce this

**Comment by bishabosha** [comment]
actually, I can reproduce, but only if `-source:future` is not on - so please could you check again if that was the issue?

**Comment by rjolly** [comment]
Yes, sorry, you have to actually have several source files:
Ord.scala
```Scala
trait Ord[T]
```
Sorted.scala
```Scala
trait Sorted[T]:
  given Ord[T] as ord = compiletime.deferred
```
SortedSet.scala
```Scala
class SortedSet[T : Ord] extends Sorted[T]
```
And (as unbelievable as it is) this last one needs to not contain the above as prefix : SortedSe2.scala
```Scala
class SortedSe2[T : Ord] extends SortedSet[T]
```
(Notice the Se2 instead of Set2)

**Comment by KacperFKorban** [comment]
I managed to minimize it into a single file, but the order of declarations is important. Or at least it's important for `MySortedSet` to be declared before `SortedSet`.

```scala
//> using scala 3.nightly
//> using options -source:future -language:experimental.modularity

class MySortedSet[T : Ord] extends SortedSet[T]

trait Ord[T]

trait Sorted[T]:
  given Ord[T] as ord = compiletime.deferred

open class SortedSet[T : Ord] extends Sorted[T]
```
