### ISSUE TITLE
Broken links to source code in API documentation

### ISSUE THREAD

**Issue by spamegg1** [scala/scala3#21201]
## Compiler version
3.4.2

## Minimized code

For example, here:

https://scala-lang.org/api/3.x/scala/collection/immutable/LazyList.html

clicking on `LazyList.scala`

## Output

![Screenshot from 2024-07-16 10-30-50](https://github.com/user-attachments/assets/302f91ab-f1ca-4b58-a603-940cbb649d0a)

## Expectation
Link should correctly go to source code.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/scala3/issues/20058
