### ISSUE TITLE
Scaladoc is years before the language and creates `opaque object`s

### ISSUE THREAD

**Issue by KacperFKorban** [scala/scala3#21228]
## Compiler version

`3.6.0-RC1-bin-20240718-bd84584-NIGHTLY`, `3.4.2`

## Minimized code

```Scala
//> using scala 3.nightly
// opaqueobject.scala

object Sth:
  opaque type A = Int
```

`scala-cli doc opaqueobject.scala`

## Output

The `object` documentation also gets an `opaque` modifier.
The `opaque type` is documented correctly.

![`opaque object` documentation](https://github.com/user-attachments/assets/39d4795e-b3d5-4190-a539-8ddbd72d4bbc)

## Expectation

The `object` documentation doesn't have an `opaque` modifier

**Comment by odersky** [comment]
It's not really opaque types. The compiler uses internally `opaque` as a flag for the object or class containing an opaque type. That won't change. It should be the job the scaladoc to filter that out.

**Comment by mbovel** [comment]
We could probably filter out `opaque` in `parseObject`?

https://github.com/scala/scala3/blob/b8c5ecb4580f29a3c66e1ad69db41113d09f2395/scaladoc/src/dotty/tools/scaladoc/tasty/ClassLikeSupport.scala#L314-L319

And could we directly remove `opaque` from `def getExtraModifiers()`?

cc @Florian3k

**Comment by KacperFKorban** [comment]
@mbovel Yes, it seems like the correct solution.

**Comment by Florian3k** [comment]
Filtering should be fine. Not so sure about removing it from `getExtraModifiers`.
