### ISSUE TITLE
Unexpected behavior in type-level pattern matching: order of cases affects outcome for non-overlapping, equally specific cases

### ISSUE THREAD

**Issue by sderdak** [scala/scala3#21250]
## Minimized code
```Scala
package sbox

//import ....typeName

object Strange:
  type int64
  type float
  type vals = int64 | float
  type mvals = mval[int64] | mval[float]

  type mval[T<:vals]
  type nullable[T<:vals]
  
  type toNullable1[T<: mvals] = T match
    case mval[`float`] => nullable[mval[float]]
    case mval[`int64`] => nullable[mval[int64]]

  type toNullable2[T<: mvals] = T match
    case mval[`int64`] => nullable[mval[int64]]
    case mval[`float`] => nullable[mval[float]]

  @main 
  def test(): Unit = {
    println(s"toNullable1[mval[float]]], yields:${typeName[toNullable1[mval[float]]]}")
    println(s"toNullable1[mval[int64]]], yields:${typeName[toNullable1[mval[int64]]]}")
    println()
    println(s"toNullable2[mval[float]]], yields:${typeName[toNullable2[mval[float]]]}")
    println(s"toNullable2[mval[int64]]], yields:${typeName[toNullable2[mval[int64]]]}")

  }

//Appendix: The code of typeName
//inline def typeName[A]: String = ${ typeNameImpl[A] }
//
//private def typeNameImpl[A](using Type[A], Quotes): Expr[String] = Expr(Type.show[A].split("\\$").last)

```

## Output
running test yields:
```
toNullable1[mval[float]]], yields:sbox.Strange.nullable[sbox.Strange.mval[sbox.Strange.float]]
toNullable1[mval[int64]]], yields:sbox.Strange.toNullable1[sbox.Strange.mval[sbox.Strange.int64]]
                                                                                ^^^^^^^^
toNullable2[mval[float]]], yields:sbox.Strange.toNullable2[sbox.Strange.mval[sbox.Strange.float]]
toNullable2[mval[int64]]], yields:sbox.Strange.nullable[sbox.Strange.mval[sbox.Strange.int64]]
                                                                                ^^^^^
```
the only diff between toNullable1 and toNullable2 is the flipped order of cases
the result is different

## Expectation
The order of cases in the type-level pattern matching should not affect the outcome. Both `ToNullable1` and `ToNullable2` should produce the same results for both `mval[float]` and `mval[int64]`.

Actual behavior:
The results differ depending on the order of cases. This leads to inconsistent and potentially confusing behavior in type-level programming.

Additional context:
 This behavior could lead to subtle bugs in type-level programming and makes reasoning about type-level code more difficult. It would be helpful to understand if this is intended behavior or if it's a bug that should be addressed.

**Comment by sjrd** [comment]
There is no bug here. That is intended. Match type cases are tried in order. If the first one matches, then it reduces. Otherwise, if the first one is "probably-disjoint" from the scrutinee, then second one is tried, etc.

Since `mval[float]` is not provably-disjoint from `mval[int64]`, when the first case matches, we cannot proceed to the second case and therefore the match type is left unreduced.

**Comment by sderdak** [comment]
thank you for answering and triaging! A good documentation would help :)
It is hard to understand that the types mval[float] and mval[int64] become provably disjoint 
if I define trait int64 and trait float.

**Comment by sjrd** [comment]
You can find the precise spec for provably-disjoint here: https://docs.scala-lang.org/sips/match-types-spec.html#disjointness
