### ISSUE TITLE
The auto-approximated bound for match types leaks type captures

### ISSUE THREAD

**Issue by sjrd** [scala/scala3#21256]
## Compiler version

since 3.4.2, still present in `main`

## Minimized code

```scala
object Test {
  type MTWithBind[X] = X match {
    case List[t] => t
  }
}
```

## Output

With `-Xprint:typer`:

```scala
    type MTWithBind[X >: Nothing <: Any] =
      X match 
        {
          case List[t @ _] => t
        }
       <: t
```

## Expectation

`t` should not appear in the inferred bound of the match type, since it is outside of its declaring scope.

Overall I'm getting increasingly uneasy about #19761. :face_with_diagonal_mouth:

**Comment by mbovel** [comment]
This issue was picked for the Scala Issue Spree of tomorrow, Monday, December 2nd. @dwijnand, @bracevac and @HarrisL2 will be working on it.
