### ISSUE TITLE
Unexpected warning when `@main` is used twice within a single object

### ISSUE THREAD

**Issue by Gedochao** [scala/scala3#21365]
## Compiler version
3.4.2, 3.3.3, 3.6.0-RC1-bin-20240810-ba2c731-NIGHTLY

## Minimized code
```scala
package baz

object Bar {
  @main def main(): Unit = println("main Bar")
  @main def bar(): Unit = println("bar Bar")
}
```

## Output
```scala
[warn] ./repro.scala:3:8
[warn] object Bar differs only in case from class bar in package baz. Such classes will overwrite one another on case-insensitive filesystems.
[warn] object Bar {
[warn]        ^
```

## Expectation
One of two:
- a better warning about using the `@main` annotation twice, if needed
- no warning, as this particular code is valid and both main methods (`baz.bar` & `baz.main`) can be accessed.

```bash
scala-cli run repro.scala --main-class-ls
# [warn] ./repro.scala:3:8
# [warn] Generated class baz.Bar differs only in case from baz.bar.
# [warn]   Such classes will overwrite one another on case-insensitive filesystems.
# [warn] object Bar {
# [warn]        ^
# baz.bar baz.main
```

## Context
Extracted out of:
- https://github.com/scala/scala3/issues/21348

**Comment by mbovel** [comment]
This issue was picked for the Scala Issue Spree of tomorrow, August 13th. @EugeneFlesselle @bracevac @jan-pieter and @nmcb will be working on it. If you have any insight into the issue or guidance on how to fix it, please leave it here.

**Comment by bracevac** [comment]
@EugeneFlesselle  @jan-pieter @nmcb we will use the following Zoom link for today:
https://epfl.zoom.us/j/63745061412

**Comment by bracevac** [comment]
The issue has nothing to do with multiple `@main` annotations. As the warning correctly points out, the naming will cause issues with non-casesensitive filenames. So there is nothing to be done here.

**Comment by som-snytt** [comment]
The other ticket is repurposed for "improved help for *all* the anomalies".

I assumed, maybe wrongly, that this issue was specifically different from the linked ticket about multiple mains named the same; this is about the unhelpful error message, about a class I didn't write, for a feature that beginners are expected to use with abandon, yet without feeling abandoned.
