### ISSUE TITLE
Anonymous givens for two different types with same name create "Duplicate definition"

### ISSUE THREAD

**Issue by AndreasKillaitis0000** [scala/scala3#21363]
## Compiler version

Scala 3.4.2

## Minimized code

```Scala
object Foo:
  class X

object Bar:
  class X

trait Show[T]:
  def show(x: T): String

def weird() = 
  given Show[Foo.X] with
    def show(x: Foo.X) = "some foo"

  given Show[Bar.X] with    // <- this is a different X!
    def show(x: Bar.X) = "some bar"
```

## Output

```scala
given_Show_X is already defined as object given_Show_X

Note that overloaded methods must all be defined in the same group of toplevel definitions
```

## Expectation

The Scala compiler should generate unique names for the given. I know I can circumvent this issue by giving the givens explicit names, but I think it should work without it.

**Comment by sjrd** [comment]
> The Scala compiler should generate unique names for the given. I know I can circumvent this issue by giving the givens explicit names, but I think it should work without it.

This is by design. We cannot generate unique names without significantly endangering binary compatibility.
