### ISSUE TITLE
Match type with opaque type among cases does not resolve

### ISSUE THREAD

**Issue by jirijakes** [scala/scala3#21366]
If opaque type is one of the cases in a match type, the match type does not resolve.

In the code below I expect `M[Char]` to resolve to `Boolean`. However, if the `case A.I` is present, it does not compile. If `case A.I` is removed, it compiles.

Underlying type of the opaque type or types in other cases do not seem to matter.

## Compiler version

3.5.0-RC6

## Minimized code

```Scala
object A:
  opaque type I = Int

type M[T] = T match
   case A.I => String // compiles without this case
   case Long => String
   case _ => Boolean

def f(m: M[Char]): Boolean = m
```

## Output

```
9 |def f(m: M[Char]): Boolean = m
  |                             ^
  |                             Found:    (m : M[Char])
  |                             Required: Boolean
  |-----------------------------------------------------------------------------
  | Explanation (enabled by `-explain`)
  |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  |
  | Tree: m
  | I tried to show that
  |   (m : M[Char])
  | conforms to
  |   Boolean
  | but none of the attempts shown below succeeded:
  |
  |   ==> (m : M[Char])  <:  Boolean
  |     ==> M[Char]  <:  Boolean
  |       ==> Char match {   case A.I => String   case Long => String   case Any => Boolean }  <:  Boolean
  |         ==> Any  <:  Boolean  = false
  |
  | The tests were made under the empty constraint
   -----------------------------------------------------------------------------
1 error found
```

## Expectation

Match type resolves with or without opaque type among the cases.

**Comment by sjrd** [comment]
As designed. The type system can neither show that `Char <: A.I` nor show that it is disjoint from it, since `A.I` is nothing but a `>: Nothing <: Any` from the point of view of `f`.

Don't mix match types and opaque type aliases. It will almost never do what you want it to. Use regular container classes instead.
