### ISSUE TITLE
Nil and LinearSeq cannot be compared

### ISSUE THREAD

**Issue by Bersier** [scala/scala3#21392]
## Compiler version

3.5.1-RC2

## Minimized code

```Scala
import scala.collection.LinearSeq

def foo[T](a: LinearSeq[T]) = a match
  case Nil => -1
  case head +: tail => head
```

### Compiler options

```
 -language:strictEquality
 -Yexplicit-nulls
```

## Compiler output

```scala
Values of types object Nil and LinearSeq[T] cannot be compared with == or !=.
```

## Expectation

No compile-error

Note: the addition of `CanEqual` givens between `Nil.type` and `LinearSeq` does not help.

**Comment by noti0na1** [comment]
It is weird that the error only happens if both flags are enabled.

**Comment by goshacodes** [comment]
Hello, one more example:
Versions: 3.3.3, 3.5.0
## Example
```scala
enum Foo:
  case Bar
  case Baz(x: String)


def foo(a: Foo) = a match
  case Foo.Bar => -1
  case _ => 0
```

## Output
Values of types Playground.Foo and Playground.Foo cannot be compared with == or !=

**Comment by noti0na1** [comment]
> ```scala
> enum Foo:
>   case Bar
>   case Baz(x: String)
> 
> 
> def foo(a: Foo) = a match
>   case Foo.Bar => -1
>   case _ => 0
> ```
> 
> ## Output
> Values of types Playground.Foo and Playground.Foo cannot be compared with == or !=

For this example, the error is not related to explicit nulls, and you need to add `derives CanEqual` to `Foo`.

**Comment by goshacodes** [comment]
> > ```scala
> > enum Foo:
> >   case Bar
> >   case Baz(x: String)
> > 
> > 
> > def foo(a: Foo) = a match
> >   case Foo.Bar => -1
> >   case _ => 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Output
> > Values of types Playground.Foo and Playground.Foo cannot be compared with == or !=
> 
> For this example, the error is not related to explicit nulls, and you need to add `derives CanEqual` to `Foo`.

Hmm, ok) Thank you.
