### ISSUE TITLE
Using full qualifier names for anonymous given naming to avoid double definition

### ISSUE THREAD

**Issue by soronpo** [scala/scala3#21406]
## Compiler version

v3.5.0

## Minimized code

```Scala
object Bar:
  trait Foo

object Baz:
  trait Foo

given Bar.Foo = ???
given Baz.Foo = ???
```

## Output

```scala
Double definition:
final lazy given val given_Foo: Playground.Bar.Foo in object Playground at line 9 and
final lazy given val given_Foo: Playground.Baz.Foo in object Playground at line 10
```

## Expectation
Naming will be according to the full select name to resolve the double definition. 
```
final lazy given val given_Bar_Foo: Playground.Bar.Foo = ???
final lazy given val given_Baz_Foo: Playground.Baz.Foo = ???
```
I'm unsure if binary compatibility is an issue here.

**Comment by sjrd** [comment]
Yes, binary and tasty and even source compatibility are issues.

No, we cannot ever change the naming of anonymous givens. It is what it is.

**Comment by soronpo** [comment]
> Yes, binary and tasty and even source compatibility are issues.
> 
> No, we cannot ever change the naming of anonymous givens. It is what it is.

@sjrd What if we only do the following in case of a double definition conflict?:
```scala
final val given_Foo: Playground.Bar.Foo = ???
final lazy given val given_Bar_Foo: Playground.Bar.Foo = given_Foo
```
That should preserve both source and binary compatibility.

**Comment by sjrd** [comment]
No, it won't. We don't know which one was added first and must be preserved. If they're separately compiled, we also don't know which one to rename.
