### ISSUE TITLE
Scala runner no longer looks for compiled classes in the current working directory

### ISSUE THREAD

**Issue by KieranP** [scala/scala3#21432]
## Compiler version

3.5.0

## Minimized code

Example from https://docs.scala-lang.org/scala3/book/taste-hello-world.html

## Output

```scala
› scalac hello.scala
› ls -la hello.*
-rw-r--r--@ 1 kieran  staff  758 25 Aug 20:45 hello$package$.class
-rw-r--r--@ 1 kieran  staff  267 25 Aug 20:45 hello$package.class
-rw-r--r--@ 1 kieran  staff  593 25 Aug 20:45 hello$package.tasty
-rw-r--r--@ 1 kieran  staff  912 25 Aug 20:45 hello.class
-rw-r--r--@ 1 kieran  staff   45 25 Aug 20:45 hello.scala
-rw-r--r--@ 1 kieran  staff  502 25 Aug 20:45 hello.tasty
› scala hello
[error]  hello is not a scala sub-command and it is not a valid path to an input file or directory.
Try viewing the relevant help to see the list of available sub-commands and options.
  scala --help
```

## Expectation

Works fine in 3.4.0. This has broken in 3.5.0.

If this has been changed intentionally, it doesn't appear in the release notes and the documentation needs updating.

`scala run hello` doesn't work either. But `scala run hello.scala` does, but it compiled the program each time.

**Comment by tgodzik** [comment]
Thanks for reporting! You don't have to actually use scalac to compile things before running. We should update the docs and make sure this is handled properly if needed.

**Comment by bishabosha** [comment]
the Programming in Scala book for Artima books recommends this pattern - which won't be rewritten

**Comment by KieranP** [comment]
@tgodzik Compiling ahead of time can come in handy for when quick starts and performance are needed. As mentioned by @bishabosha  , there are books and many online tutorials that reference using `scalac` to compile and then `scala` to execute. If this is no longer possible, the new method of compiling/executing should be clearly shown in the console when you try to use the older method.

**Comment by tgodzik** [comment]
Sure, makes sense! I am just trying to offer an alternative for now.

>  Compiling ahead of time can come in handy for when quick starts and performance are needed.

As a total side note, you can also do `scala --power package --native  .` which will create a native executable (or you can skip native, use jvm or use native image).

**Comment by KieranP** [comment]
@tgodzik Interesting, I hadn't heard about Scala native. But it seems like it has a bit to go in order to catch up with the JVM in terms of performance. Even with full optimisation turned on, native is 3.2x slower than JVM.

```
JVM: 80335 iterations - World Tick (L: 0.105; A: 0.119) - Rendering (L: 0.121; A: 0.134)
Native Release-fast: 17422 iterations- Tick (L: 0.597; A: 0.665) - Rendering (L: 0.841; A: 0.957)
Native Release-full: 24971 iterations - Tick (L: 0.320; A: 0.352) - Rendering (L: 0.651; A: 0.736)
```

**Comment by tgodzik** [comment]
Another option is to generate native image with ` scala --power package --native-image  .` but not sure if the performance will be much better. However, both are very useful where start up time matters. JVM is quite good at performance otherwise and might hard to beat.

**Comment by WojciechMazur** [comment]
The performance of Scala Native can sometimes vary depending on the code being compiled - because it needs to reimplement parts of Java Standard Library some implementations might not be on par with JVM. However, in the past, [we've observed](https://virtuslab.com/blog/technology/scala-native-performance/#summary) that in some benchmarks it was on par or faster than JVM, in other ones, it could have been slower.  
We'll always be grateful for your providing us (Scala Native) with snippets of code/benchmarks that execute significantly slower than JVM. Based on that, we should be able to improve performance like we did recently during [pure Scala 1 billion rows challange](https://github.com/lbialy/1brc/tree/scala-and-scala-native/scala)

**Comment by KieranP** [comment]
@WojciechMazur Thanks for the information. I have created Conway's Game of Life in 25+ languages, including Scala. All implementations are as identical as they can be, to give as best a comparison of features and performance. You can find the Scala version here: https://github.com/KieranP/Game-Of-Life-Implementations/tree/master/scala - Using the JVM, Scala ranks in at 4th in the speed rankings. As it currently stands, Scala Native would place about 23rd.

**Comment by Gedochao** [comment]
So this is intentional behaviour, which is a part of SIP-46. The new runner does not support (nor will it support) this syntax.
We should document it clearly (as we have indeed missed it) and that will be tracked under https://github.com/VirtusLab/scala-cli/issues/3132

> the Programming in Scala 5th edition (Odersky, Spoon, Venners) recommends this pattern - which won't be rewritten

We can't escape some behaviours to be changed, we have a brand new `scala` runner in Scala 3.5.0.

Nothing to do here, closing this.

**Comment by lrytz** [comment]
If someone needs a quick workaround, it seems the `bin` directory has a `scala_legacy` script that is equivalent to the `scala` script before 3.5.

**Comment by olhotak** [comment]
Is there a Scala CLI command for the use case of running a compiled Scala `.class` file when one doesn't have the original corresponding `.scala` source file?

`scala_legacy` works for this use case in 3.5.0 but it gives a deprecation warning that recommends upgrading to Scala CLI.

Is the intended migration path for this use case to invoke the `java` VM directly (manually adding the Scala standard library to the classpath)?

**Comment by tgodzik** [comment]
Would `scala run --classes .` work for you? That should just add the current directory to the classpath

**Comment by olhotak** [comment]
Yes, that works for my use case. Thank you.
