### ISSUE TITLE
Scala-3.5.0 runner requires JDK-17+ on BSD

### ISSUE THREAD

**Issue by catap** [scala/scala3#21526]
## Compiler version

```
Scala compiler version 3.5.0 -- Copyright 2002-2024, LAMP/EPFL
```

## Minimized example

```
$ env JAVA_HOME=/usr/local/jdk-1.8.0 scala
```

## Output

```
scala $ env JAVA_HOME=/usr/local/jdk-1.8.0 scala 
Error: java.lang.Exception: Unrecognized OS: openbsd
For more details, please see '/usr/ports/lang/scala/.scala-build/stacktraces/1725217762-8871160887746307735.log'
scala $ cat /usr/ports/lang/scala/.scala-build/stacktraces/1725217762-8871160887746307735.log
java.lang.Exception: Unrecognized OS: openbsd
  coursier.jvm.JvmIndex$.defaultOs(JvmIndex.scala:173)
  scala.build.internal.OsLibc$.jvmIndexOs$lzyINIT1(OsLibc.scala:59)
  scala.build.internal.OsLibc$.jvmIndexOs(OsLibc.scala:58)
  scala.cli.javaLauncher.JavaLauncherCli$.runAndExit(JavaLauncherCli.scala:22)
  scala.cli.ScalaCli$.main0(ScalaCli.scala:251)
  scala.cli.ScalaCli$.main(ScalaCli.scala:117)
  scala.cli.ScalaCli.main(ScalaCli.scala)
scala $
```

## Expectation

Should work.

The root cause of this issue is https://github.com/scalacenter/bloop/pull/2355 which introduced this lines https://github.com/scalacenter/bloop/blob/v2.0.0/cli/src/main/scala/bloop/cli/util/OsLibc.scala#L64-L70 whiich uses on JDK before 17 https://github.com/coursier/coursier/blob/v2.1.10/modules/jvm/src/main/scala/coursier/jvm/JvmIndex.scala#L154-L160 where an exception for non Windows, Linux or Darwin.

**Comment by ritschwumm** [comment]
@Gedochao maybe it's possible to at least have a more helpful error message?

**Comment by catap** [comment]
@ritschwumm and document it somewhere!

**Comment by Gedochao** [comment]
> maybe it's possible to at least have a more helpful error message?

@ritschwumm I created a dedicated ticket, let's track it under:
- https://github.com/VirtusLab/scala-cli/issues/3146


> and document it somewhere!

@catap Created tickets:
- https://github.com/VirtusLab/scala-cli/issues/3148
- https://github.com/VirtusLab/scala-cli/issues/3147

**Comment by Gedochao** [comment]
> include JVM indexes for BSD in https://github.com/coursier/jvm-index

I created an issue upstream:
- https://github.com/coursier/coursier/issues/3059
