### ISSUE TITLE
Better error reporting is required for inlined non-immutable paths

### ISSUE THREAD

**Issue by soronpo** [scala/scala3#21538]
As discovered in #16804 and raised again in #17181 and #21536, it is clear that better error reporting is required to prevent further ticket opening, by suggesting to remove the `inline` from the dependent argument in the compiler error message. 

## Compiler version

v3.5.0

## Minimized code

```Scala
trait Bar[T]
given [T]: Bar[T] with {}
inline def foo[V](inline value: V)(using Bar[value.type]) : Unit = {} //error
```

## Output

```scala
(value : V) is not a valid singleton type, since it is not an immutable path
inline def foo[V](inline value: V)(using Bar[value.type]) : Unit = {}
```

## Expectation
The compiler should provide a hint to remove the `inline` keyword from the dependent value to resolve the error.

**Comment by soronpo** [comment]
cc @Gedochao

**Comment by mbovel** [comment]
Note for future readers: Nicolas explained why inline values cannot be stable paths in https://github.com/scala/scala3/issues/16804#issuecomment-1413408550.

What would you expect as a better error message? Something like the following?

```
(value : V) is not a valid singleton type, since it is not an immutable path. Inline parameters are not considered immutable paths and cannot be used as singleton types. Removing the `inline` qualifier from the `value` parameter may help resolve this issue.
```

**Comment by mbovel** [comment]
To solve this, I suggest to special-case the `NotAPath` message:

https://github.com/scala/scala3/blob/b8c5ecb4580f29a3c66e1ad69db41113d09f2395/compiler/src/dotty/tools/dotc/reporting/messages.scala#L1819-L1825

One can check if `tp` refers to a term symbol that is an inline parameter there, and display additional information if it is the case.

**Comment by soronpo** [comment]
> Note for future readers: Nicolas explained why inline values cannot be stable paths in [#16804 (comment)](https://github.com/scala/scala3/issues/16804#issuecomment-1413408550).
> 
> What would you expect as a better error message? Something like the following?
> 
> ```
> (value : V) is not a valid singleton type, since it is not an immutable path.
> Inline parameters are not considered immutable paths and cannot be used as
> singleton types. Removing the `inline` qualifier from the `value` parameter
> may help resolve this issue.
> ```

Seems good. I think the compiler started to have a standardize a format for providing hints.
So it will look better with:
```
(value : V) is not a valid singleton type, since it is not an immutable path.
Inline parameters are not considered immutable paths and cannot be used as
singleton types. 

Hint: Removing the `inline` qualifier from the `value` parameter
may help resolve this issue.
```

**Comment by mbovel** [comment]
This issue was picked for the Scala Issue Spree of tomorrow, September 24th. @HarrisL2, someone yet unknown and I will be working on it.
