### ISSUE TITLE
Regression on path dependent types from 3.2

### ISSUE THREAD

**Issue by AnnelineD** [scala/scala3#21536]
## Compiler version

Works on 3.2.2 and fails on 3.3.2 and 3.5.0.

## Minimized code

```Scala
object PatchG:
   inline def apply[EL, MG <: DNIELMG[EL]](inline mg: MG)(inline ptps: List[(mg.Node | C.type, mg.Node | C.type)]): PatchG[EL, MG]
```
https://github.com/Adam-Vandervorst/LLGraph/blob/10f010e536beb1c8fb5f5a8bf80f7c308dc72768/src/main/scala/be.adamv.llgraph/graphs/PatchG.scala#L112

## Output

```scala
[error] -- [E083] Type Error: /home/anneline/IdeaProjects/LLGraph/src/main/scala/be.adamv.llgraph/graphs/PatchG.scala:112:76 
[error] 112 |  inline def apply[EL, MG <: DNIELMG[EL]](inline mg: MG)(inline ptps: List[(mg.Node | C.type, mg.Node | C.type)]): PatchG[EL, MG] =
[error]     |                                                                            ^^
[error]     |(mg : MG) is not a valid type prefix, since it is not an immutable path
[error]     |---------------------------------------------------------------------------
[error]     | Explanation (enabled by `-explain`)
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     | An immutable path is
[error]     |  - a reference to an immutable value, or
[error]     |  - a reference to `this`, or
[error]     |  - a selection of an immutable path with an immutable value.
[error]      ---------------------------------------------------------------------------
```

## Expectation
To compile, since the inlined version does type-check.
Example usage:
```scala
  val rhs = DNIELMG[Char]()
  val r = rhs.newNodes(2)
  rhs.connect(r(0), r(0), 'b')

  val rpg = PatchG[Char, rhs.type](rhs)(List(C -> r(0), r(1) -> C))
```
https://github.com/Adam-Vandervorst/LLGraph/blob/10f010e536beb1c8fb5f5a8bf80f7c308dc72768/src/test/scala/PatchGTest.scala#L24

**Comment by AnnelineD** [comment]
I guess this relates to https://github.com/scala/scala3/issues/16804 but the answer there is not satisfactory, since dropping the path-dependent-types from this (and its down the line) project seriously hampers its type safety.

What is the workaround? Can this be expressed via implicits somehow since they are unique (the cause identified in @soronpo his issue)?

**Comment by Gedochao** [comment]
cc @jchyb

**Comment by jchyb** [comment]
Hi @AnnelineD. Looking at the linked project, it looks to me like it should be enough to just drop the inline modifier from the `mg` parameter, since its "inlineness" does not seem to be required anywhere:
```scala
object PatchG:
   inline def apply[EL, MG <: DNIELMG[EL]](mg: MG)(inline ptps: List[(mg.Node | C.type, mg.Node | C.type)]): PatchG[EL, MG]
```
This will make the `mg` into an immutable path, and inline into roughly the same form as in the `Expectation` field, with the `val rhs = DNIELMG[Char]()` being a separate val (with an immutable path), instead of being directly inlined.

**Comment by soronpo** [comment]
@Gedochao I'm looking again on the original issue, and it seems that people run into it several more times and spent time to minimize it. I think we should change the problem to a reporting issue. The compiler needs to suggest to remove the `inline` to solve the problem.

**Comment by Gedochao** [comment]
Closing this, the reporting improvement should be tracked under #21538
