### ISSUE TITLE
For comprehension bug when using type casting

### ISSUE THREAD

**Issue by road21** [scala/scala3#21544]
## Compiler version

3.5.0, 3.3.3

## Minimized code

https://scastie.scala-lang.org/road21/GozkhzC7QXaGpkbM7mNYUg/3

```scala
for {
  (x: Any) <- (List[Boolean]())
} yield x
```

## Output

Compile error:
```
[error] cannot test if value of type Boolean is a reference of class Object
[error]   (x: Any) <- (List[Boolean]())
[error]    ^^^^^^
```

## Expectation

No compiler error

Same code works fine in Scala 2.13

**Comment by Gedochao** [comment]
@sjrd should this actually compile, or is this not supported for a reason? (in which case it'd just need a better error message)

**Comment by sjrd** [comment]
Looks like a bug to me. It should compile.
