### ISSUE TITLE
Incremental compilation in Scala 3.5.0 compiles too many files

### ISSUE THREAD

**Issue by OndrejSpanel** [scala/scala3#21594]
## Compiler version

3.5.0

(I have tested the issue does not exists with (2.13.14, 3.0.0. 3.2.0 or 3.4.2)

## Minimized code

ClassA.scala:

```Scala
object ClassA {
  def a: String = "b"
}
```

Main.scala:

```Scala
object Main {
  def main(args: Array[String]): Unit = {
    println("Hello world!x")
  }
}
```

build.sbt:

```
scalaVersion := "3.5.0"
```

- From SBT use `compile`
- Change "b" in ClassA.scala to "a"
- From SBT use `compile `again.

## Output

> [info] compiling 2 Scala sources to C:\Dev\inc\target\scala-3.5.0\classes ...

## Expectation

Only 1 file should be compiled. There is no reason to compile both. This is the output I get with all previous compiler versions:

> [info] compiling 1 Scala source to C:\Dev\inc\target\scala-3.4.2\classes ...

## Note

I observe much worse incremental compilation in my real world project. Even when doing just a small change in my code, most of files are compiled and compilation takes very long. It is hard to be sure the issue here is representative of the real issue, but it certainly looks suspicious and strange.

**Comment by OndrejSpanel** [comment]
Another note: I have just tested 3.5.0-RC7 and I do not see the issue with it. I am not sure what that means - I though 3.5.0 is identical to its RC7?

**Comment by som-snytt** [comment]
FWIW, I could not reproduce with sbt 1.10.1, JVM 17.

```
➜  i21594-incr git:(main) ✗ ll ./target/scala-3.5.0/classes
total 24K
-rw-r--r-- 1 amarki amarki 671 Sep 14 17:03 'ClassA$.class'
-rw-r--r-- 1 amarki amarki 280 Sep 14 17:03  ClassA.class
-rw-r--r-- 1 amarki amarki 526 Sep 14 17:03  ClassA.tasty
-rw-r--r-- 1 amarki amarki 851 Sep 14 17:01 'Main$.class'
-rw-r--r-- 1 amarki amarki 278 Sep 14 17:01  Main.class
-rw-r--r-- 1 amarki amarki 631 Sep 14 17:01  Main.tasty
```
and
```
sbt:i21594-incr> compile
[info] compiling 2 Scala sources to .../i21594-incr/target/scala-3.5.0/classes ...
[success] Total time: 3 s, completed Sep 14, 2024, 5:01:20 PM
sbt:i21594-incr> compile
[success] Total time: 0 s, completed Sep 14, 2024, 5:03:28 PM
sbt:i21594-incr> compile
[info] compiling 1 Scala source to .../i21594-incr/target/scala-3.5.0/classes ...
[success] Total time: 0 s, completed Sep 14, 2024, 5:03:57 PM
sbt:i21594-incr>
```

**Comment by OndrejSpanel** [comment]
I confirm I cannot reproduce this on WSL as well. 

What is more important for me, I cannot reproduce it on GitHub runner, which is where I observe my real issue (Linux, Java 21, action/cache used):

https://github.com/OndrejSpanel/incremental-repro/actions/runs/10869198352/job/30160068349

Still I reproduce in on Windows11 x64, Java 21 and it makes investigating my real issue more difficult.

**Comment by OndrejSpanel** [comment]
I am even more confused now 😕. I reproduced in at 1:36, I reproduced in at 9:00, but not now.

**Comment by OndrejSpanel** [comment]
It seems it is some interaction with the IntelliJ IDE. When I have the IDE open and it is set to use Compiler highlighting, it causes sbt to act differently (and build more).

I still see the issue with unexpectedly large incremental compilations on my github runners, but this issue does not seem to be related to it at all.
