### ISSUE TITLE
`-Ycheck:all` preventing a legit method definition

### ISSUE THREAD

**Issue by joan38** [scala/scala3#21600]
Hi,

I'm not able to create a function with `-Ycheck:all` enabled because of [this check](https://github.com/scala/scala3/blob/main/compiler/src/dotty/tools/dotc/transform/TreeChecker.scala#L455-L459) called [here](https://github.com/scala/scala3/blob/main/compiler/src/dotty/tools/dotc/transform/TreeChecker.scala#L649).
This check looks at if the method info is a `MethodicType` or a `AnnotatedType`.
How can one define a method  `Symbol.newMethod(.....)` without any group parameter and still pass this check?
As in: `def foo: String = "Hello"`
And not: `def foo(): String = "Hello"`

## Compiler version

`3.5.0`

Thanks

**Comment by lrytz** [comment]
Probably https://github.com/scala/scala3/blob/3.5.0/compiler/src/dotty/tools/dotc/core/Types.scala#L3797-L3798,
for example https://github.com/scala/scala3/blob/3.5.0/compiler/src/dotty/tools/dotc/core/Definitions.scala#L300.

But please use https://contributors.scala-lang.org/ or discord for questions.

**Comment by joan38** [comment]
@lrytz These are scala-compiler package code. We are using Scala Macros' `QuotesImpl`.
[Here](https://github.com/joan38/moulin/blob/main/src/com/goyeau/moulin/command/WildCard.scala#L174) is an example of where we create a `TypeRepr`. When there are params (even if empty), we create a `MethodType` but if not we just put the `TypeRepr` on the created `def`.

So the issue I'm reporting is that `QuotesImpl` does not have any way to create a `def` without `()` param.
