### ISSUE TITLE
Compiler Crashes when Upper-Bounding a Class' Type Parameter with caps.Capability under -Xprint:cc

### ISSUE THREAD

**Issue by bracevac** [scala/scala3#21646]
## Compiler version

`3.6.0-RC1-bin-20240924-3f4fee2-NIGHTLY-git-3f4fee2`

## Minimized code

```Scala
import language.experimental.captureChecking
import caps.Capability

trait File extends Capability

class Resource[T <: Capability](gen: T):
  def use[U](f: T => U): U = 
    f(gen)

@main def run = 
  val myFile: File = ???
  val r = Resource(myFile)
  ()
```

Edit: minimized further

## Output (click arrow to expand)
<details>

```scala
[error] ## Exception when compiling 1 sources to /Users/oliver/playground/caps/caps/target/scala-3.6.0-RC1-bin-20240924-3f4fee2-NIGHTLY/classes
[error] dotty.tools.dotc.core.TypeError$$anon$1: invalid new prefix [T <: box caps.Capability^] =>> Test.Resource[box T^] cannot replace Test.Resource in type (Test.Resource#<init> : [T <: box caps.Capability^](gen: T^): Test.Resource[T])
```
</details>

**Comment by odersky** [comment]
I could not reproduce this. #21659 contains the example as a test case (21646.scala). This one compiles with errors but does not crash.

**Comment by bracevac** [comment]
@odersky The exception appears when **BOTH** the `-Xprint:cc` compiler option is enabled **AND** having the upper bound `T <: Capability` in `class Resource`.

Say this is in `Caps.scala`:
```scala
//> using scala 3.6.0-RC1-bin-20240918-be10596-NIGHTLY
import language.experimental.captureChecking
import caps.Capability

trait File extends Capability

class Resource[T <: Capability](gen: T):
  def use[U](f: T => U): U = 
    f(gen)

@main def run = 
  val myFile: File = ???
  val r = Resource(myFile)
  ()
```
and we run 
```bash
scala compile Caps.scala -O -Xprint:cc
```
(resp. with `scala-cli` pre 3.5) then compiler will crash with an exception. It will also happen when compiling via a traditional `sbt` project using the nightly compiler build.

On the other hand, if we remove the bound `<: Capability` from `T`, then the compiler exception **will not occur** even if `-Xprint:cc` is enabled.

**Comment by bracevac** [comment]
I can also confirm that this happens with the latest nightly `//> using scala 3.nightly`

**Comment by bracevac** [comment]
The problem appears to be in the `show` method of class `Recheck` respectively the TreeMap used in `addRecheckedTypes`.
