### ISSUE TITLE
Match types are unable to correctly handle opaque types.

### ISSUE THREAD

**Issue by wz7982** [scala/scala3#21679]
## Compiler version

3.5.0

## Minimized code

```Scala
object A:
    opaque type Str = String

object B:
    type F[X] = X match
        case A.Str => String
        case Int => Boolean
        case Boolean => Int

    val x1: F[A.Str] = ""
    val x2: F[Int] = true
    val x3: F[Boolean] = 1
```

## Output

compile error.

## Expectation

This issue hinders the ability to match Tuple and NamedTuple within Match Types.

**Comment by sjrd** [comment]
As expected. There are countless issues already closed as "as designed" on the topic.

**Comment by wz7982** [comment]
> As designed. There are countless issues already closed as "as designed" on the topic.

How to calculate opaque type?
