### ISSUE TITLE
Review NamedTuple methods

### ISSUE THREAD

**Issue by odersky** [scala/scala3#21685]
## Compiler version

3.6

## Minimized example

`NamedTuple` is leaving @experimental status. Before it can be released as part of 3.6, we should do a last sweep over its methods to see whether we need anything changed.

**Comment by WojciechMazur** [comment]
Is there anything left to do about Named Tuples before 3.6.0?  I can see 1 open PR related to named tuples - #21710

**Comment by EugeneFlesselle** [comment]
Closed with #21710

**Comment by EugeneFlesselle** [comment]
Closed with #21710
