### ISSUE TITLE
New givens syntax does no logger accepts valid given defintions

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21768]
Based on OpenCB failure in `jphmrst/scala-automata` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/11300366582/job/31433152843)
Affects also: 
 - `rssh/cps-async-connect` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/11300416468/job/31433780958)

The new givens syntax and its changes to the parser no longer accept valid old (pre 3.6.0) givens syntax, in cases when type of the type-class is moved to the next line. It's a common issue that might be introduced by automatic code formatters when dealing with long names or signatures of given. 

## Compiler version

Last good release: 3.6.0-RC1-bin-20241003-a672e05-NIGHTLY
First bad release: 3.6.0-RC1-bin-20241005-6fa81cf-NIGHTLY

Bisect points to: 14acdc06067a202f381fa9066a961cebb1314d6a

## Minimized code

```Scala
trait Typeclass[T]:
  def op(v: T): Unit

given namedGivenWithLongName[T]:
  Typeclass[T] with
    override def op(v: T): Unit = ???

given otherNamedGivenWithLongName[T]:
  Typeclass[T] = new Typeclass[T]:
    override def op(v: T): Unit = ???
```

## Output

```scala
[error] ./test2.scala:5:16
[error] end of statement expected but 'with' found
[error]   Typeclass[T] with
[error]                ^^^^
[error] ./test2.scala:4:7
[error] Not found: type namedGivenWithLongName
[error] given namedGivenWithLongName[T]:
[error]       ^^^^^^^^^^^^^^^^^^^^^^
[error] ./test2.scala:4:30
[error] Not found: type T
[error] given namedGivenWithLongName[T]:
[error]                              ^
[error] ./test2.scala:5:13
[error] Not found: type T
[error]   Typeclass[T] with
[error]             ^
[error] ./test2.scala:5:3
[error] Not found: Typeclass
[error]   Typeclass[T] with
[error]   ^^^^^^^^^
```

## Workaround 

Compile with `-source:3.5`

## Expectation
It should compile and be parsable until deprecating the old syntax.

**Comment by Gedochao** [comment]
cc @odersky
