### ISSUE TITLE
Regression in typer for named arguments of infix methods in `ghostdogpr/caliban`

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21767]
Based on OpenCB failure for `ghostdogpr/caliban` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/11300416468/job/31433721499)
Affects also: 
- `openmole/container` - [build-logs](https://github.com/VirtusLab/community-build3/actions/runs/11300366582/job/31433236710)
- `scala-stm/scala-stm` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/11300416468/job/31433806894)
- `shopstic/caliban` (fork of project above) - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/11300366582/job/31433152979)
- `tarao/record4s` - [builds logs](https://github.com/VirtusLab/community-build3/actions/runs/11300416468/job/31433735294)
- `tpolecat/atto` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/11300416468/job/31433756144)
- `algolia/algoliasearch-client-scala` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/11300416468/job/31433714877)

The new behaviour might have become present by the stabilization of named tuples. Previously named tuples syntax was not tried without an explicit experimental flag enabled.

## Compiler version
Last good release: 3.6.0-RC1-bin-20241003-a672e05-NIGHTLY
First bad release: 3.6.0-RC1-bin-20241005-6fa81cf-NIGHTLY

Bisect points to 87cdbc8c7851830c16de0c8c828cde0f7cd0ce48

## Minimized code

```Scala
trait GraphQLRequest
sealed trait SelectionBuilder[+A]:
  def toGraphQL[A1 >: A](queryName: Option[String] = None): GraphQLRequest = ???

trait Character
trait Field[A] extends SelectionBuilder[A]

def query = 
  val field: Field[Character]  = ???
  val works = field.toGraphQL(queryName = Some("GetCharacter"))
  val fails = field `toGraphQL` (queryName = Some("GetCharacter"))
```

## Output

```scala
-- Error: /Users/wmazur/projects/sandbox/test.scala:11:44 ----------------------
11 |  val fails = field `toGraphQL` (queryName = Some("GetCharacter"))
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |method toGraphQL in trait SelectionBuilder: (queryName: Option[String]): GraphQLRequest does not have a parameter equeryName
```

## Expectation
The compiler should interpret infix apply as list of arguments instead of named tuple.

**Comment by Gedochao** [comment]
cc @odersky

**Comment by odersky** [comment]
> The compiler should interpret infix apply as list of arguments instead of named tuple.

No, it should not. Argument syntax should be tied to regular method calls, An infix operator takes two expressions; there is no argument list in the traditional sense. Another case where this matters is
```scala
  a *: (b, c)
```
This should really preprend `a` to the tuple `(b, c)`. Right now it's a type error because the right operand is treated like an argument list. We want to get away from that. Named tuples are just one bit where this problem manifests itself.

Workaround:
```scala
  val fails = field.toGraphQL(queryName = Some("GetCharacter"))
```
It's a lot clearer anyway.

As with the other named tuple problem we should try to do a migration warning and offer a rewrite rule.

**Comment by ghostdogpr** [comment]
I agree that this code was weird, I fixed it in Caliban: https://github.com/ghostdogpr/caliban/pull/2440

**Comment by mbovel** [comment]
Tracking issue: https://github.com/scala/scala3/issues/21681.
Work in progress for the warning: https://github.com/scala/scala3/pull/21565
