### ISSUE TITLE
Regression in typer for closure body treated as named tuple

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21770]
Based on OpenCB failure in `scala-native/scala-native` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/11300416468/job/31433804534)

Related #21767  

## Compiler version

Last good release: 3.6.0-RC1-bin-20241003-a672e05-NIGHTLY
First bad release: 3.6.0-RC1-bin-20241005-6fa81cf-NIGHTLY

Bisect points to https://github.com/scala/scala3/commit/87cdbc8c7851830c16de0c8c828cde0f7cd0ce48

## Minimized code

```Scala
@main def Test = {
  var cached: Option[scala.Double] = None
  val spliterator: java.util.Spliterator.OfDouble = ???
  spliterator.tryAdvance((e: Double) => (cached = Some(e)))
}
```

## Output

```scala
[error] ./test.scala:4:3
[error] None of the overloaded alternatives of method tryAdvance in trait OfDouble with types
[error]  (x$0: java.util.function.Consumer[? >: Double]): Boolean
[error]  (x$0: java.util.function.DoubleConsumer): Boolean
[error] match arguments (Double² => (cached : Some[Double²]))
[error] 
[error] where:    Double  is a class in package java.lang
[error]           Double² is a class in package scala
[error]   spliterator.tryAdvance((e: Double) => (cached = Some(e)))
```

## Expectation
Should compile

**Comment by Gedochao** [comment]
cc @odersky

**Comment by odersky** [comment]
Yes, that will no longer work. Workarounds:
```scala
spliterator.tryAdvance((e: Double) => {cached = Some(e)})
```
Or, better:
```scala
spliterator.tryAdvance { (e: Double) => cached = Some(e) }
```scala
Or:
spliterator.tryAdvance: (e: Double) => 
  cached = Some(e)
```
Each of these is clearer than the original.

One thing we can do is a migration hint with a rewrite rule.
