### ISSUE TITLE
Switch Language Feature 

### ISSUE THREAD

**Issue by Moamen189** [scala/scala3#21854]
### Problem Statement
Currently, SpeedTyper.dev only supports Scala, and there is no way for users to switch languages. This limits the accessibility and flexibility of the application, especially for users who want to practice typing in different languages.

### Proposed Solution
Add a "Switch Language" functionality to the application. This would allow users to easily switch between supported languages within the UI.

### Requirements
- **UI Component:** Create a dropdown or button that lists all supported languages.
- **Localization:** Ensure all app components are localized for different languages.
- **Persistence:** Save the selected language preference using browser storage or user settings.

### Additional Considerations
- Identify popular languages and prioritize support.
- Handle RTL (Right-to-Left) and LTR (Left-to-Right) text alignment based on selected languages.
- Potentially include a default language option based on browser settings.

### Benefits
This feature would enhance the overall user experience by making SpeedTyper.dev more inclusive and accessible to a global audience.

**Comment by Gedochao** [comment]
@Moamen189 was this meant to be raised in https://github.com/codicocodes/speedtyper.dev?

**Comment by Moamen189** [comment]
@Gedochao  yes can add some of programming Language that user can type in
