### ISSUE TITLE
False-positive `Unreachable case` warning for mix-in type test

### ISSUE THREAD

**Issue by ivan-klass** [scala/scala3#21860]
## Compiler version
3.5.2

https://scastie.scala-lang.org/7iPISGKwTfOBxOKWIRIiaw

## Minimized code
```Scala

trait Figure

sealed trait Corners {
  self: Figure =>
}

enum Shape extends Figure:
  case Triange extends Shape with Corners
  case Square extends Shape with Corners
  case Circle extends Shape
  case Ellipsis extends Shape


def hasCorners(s: Shape): Boolean = s match
  case hasCorners: Corners => true //  <--- reported as `Unreachable case`
  case _ => false

println(hasCorners(Shape.Circle))

```

## Output
>warning: Unreachable case
```scala
true
```

## Expectation
```scala
true
```

**Comment by Gedochao** [comment]
Last good stable version: 3.3.4
First bad stable version: 3.4.0

It seems bisect is failing a lot, the cause could be in any of the following commits:
1b2a16ee043140826f697f2e10c8da7e7cb6df39
f432d08f98c43e6a1607e48d13212a704e7587fd
2dd9f45b5a5ecce2e3ee60400089f8aa286b751c
ec097a948b5a10a0d1d150503cef4d26a8ab527a

cc @sjrd
