### ISSUE TITLE
Scaladoc for `Tuple` has missing methods

### ISSUE THREAD

**Issue by SethTisue** [scala/scala3#21928]
https://www.scala-lang.org/api/current/scala/Tuple.html is missing `apply` and `head` (for starters, maybe others are missing too?)

I don't have a guess about why those methods in particular might be missing

whatever's going on here, it makes me wonder how pervasive the problem is, like how many other methods might be missing elsewhere, too

**Comment by Gedochao** [comment]
cc @Florian3k

**Comment by sjrd** [comment]
They're in `NonEmptyTuple`:
https://www.scala-lang.org/api/current/scala/NonEmptyTuple.html

We *just* moved them up to `Tuple` yesterday:
https://github.com/scala/scala3/pull/21291

so the online Scaladoc wouldn't display them yet.

**Comment by SethTisue** [comment]
ohhhhh
