### ISSUE TITLE
Scaladoc: better support for named tuples

### ISSUE THREAD

**Issue by Florian3k** [scala/scala3#22065]
Currently named tuples such as `(name : String, age : Int)` are displayed as `NamedTuple[("name", "age"), (String, Int)]`. This can be improved, to be displayed the same way as in the source code.

**Comment by jchyb** [comment]
I suspect we probably also need to expose `defn.NamedTupleTypeRef` and `defn.NamedTupleModule` in the quotes reflect API, for both this and macros
