### ISSUE TITLE
Dynamic doesn't compile with Typeclass

### ISSUE THREAD

**Issue by sequencer** [scala/scala3#22158]
## Compiler version

3.5.2

## Minimized code

```Scala
import scala.language.dynamics

trait DynamicHello[E] extends Dynamic:
  extension (ref: E)
    def selectDynamic(
      field: String
    ): Any

given DynamicHello[String] with
  extension (ref: String)
    override def selectDynamic(field: String) = s"Hello $field"

// Doesn't compile with error:
// value hello is not a member of String [15:6]
def badHello(str: String) =
  str.hello

// compile, and prove `DynamicHello[String]` does give to `String`
def goodHello(str: String) =
  str.selectDynamic("hello")
```

## Output

```scala
[info] compiling 1 Scala source to xxx ...
[error] -- [E008] Not Found Error: Example.scala:15:6
[error] 18 |  str.hello
[error]    |  ^^^^^^^^^
[error]    |  value hello is not a member of String
[error] one error found
```

May relate to #17106

**Comment by sjrd** [comment]
As designed. The spec specifically forbids the `Dynamic` treatment after an implicit conversion, which also covers extension methods.

**Comment by sequencer** [comment]
Hi, @sjrd can you point out the source of spec here? I think this issue is similar with #17106

**Comment by sjrd** [comment]
https://www.scala-lang.org/files/archive/spec/3.4/06-expressions.html#dynamic-member-selection

Notice

> assuming `e`'s type conforms to `scala.Dynamic`

For it to *conform* to `scala.Dynamic`, it must be a true subtype. It cannot *become* a `scala.Dynamic` after an implicit conversion.
