### ISSUE TITLE
Scala 3.6.2 download no longer contains scala3-3.6.2 folder

### ISSUE THREAD

**Issue by francisdb** [scala/scala3#22194]
This broke the https://github.com/sbt/docker-sbt/pull/313 build

```
➜  mkdir test
➜  test curl -fsL --show-error https://github.com/lampepfl/dotty/releases/download/3.5.2/scala3-3.5.2.tar.gz | tar xfz - -C ./test
➜  test ll test
total 0
drwxr-xr-x  6 francisdb  staff   192B 11 dec 16:31 scala3-3.5.2
```

```
➜  test mkdir test2
➜  test curl -fsL --show-error https://github.com/lampepfl/dotty/releases/download/3.6.2/scala3-3.6.2.tar.gz | tar xfz - -C ./test2
➜  test ll test2
total 8
-rw-r--r--  1 francisdb  staff    69B  9 dec 13:45 VERSION
drwxr-xr-x  9 francisdb  staff   288B  9 dec 13:50 bin
drwxr-xr-x  5 francisdb  staff   160B  9 dec 13:50 lib
drwxr-xr-x  8 francisdb  staff   256B  9 dec 13:50 libexec
drwxr-xr-x  7 francisdb  staff   224B  9 dec 13:50 maven2
```

Feel free to close this if on purpose. Will work around it in the sbt docker image.

**Comment by WojciechMazur** [comment]
The previous intermediate directory was introduced by a bug, we've observed and fixed this issue in coursier as well https://github.com/coursier/apps/pull/256  
Probably a won't fix

Also a hint - you can update links to use `scala/scala3` instead of `lampepfl/dotty`

**Comment by mario-grgic** [comment]
This is worse, extracted `./bin/scala` bash script does not find `scala-cli.jar` since it does not correctly find `../libexec` directory relative to itself. It is instead expecting to find `scala-cli.jar` in the same directory where the `scala` shell script is located.

**Comment by WojciechMazur** [comment]
> This is worse, extracted `./bin/scala` bash script does not find `scala-cli.jar` since it does not correctly find `../libexec` directory relative to itself. It is instead expecting to find `scala-cli.jar` in the same directory where the `scala` shell script is located.
> 

There's already fix for that, would be shipped in 3.6.3 https://github.com/scala/scala3/pull/22185

**Comment by WojciechMazur** [comment]
Seems like it was our mistake, as we're getting more reports of problems related to this issue. 

We're going to revert layout of archives to the state from before release 3.6 and follow the (Well formed SDK archives format)[https://github.com/sdkman/sdkman-cli/wiki/Well-formed-SDK-archives] described by Sdkman 

We should be able to repackage and replace release artifacts for a hotfix for 3.6.2

**Comment by WojciechMazur** [comment]
Both of the mentioned issues should be fixed already in republished GH release artifacts

**Comment by francisdb** [comment]
Fix confirmed, sbt docker images built successfully
