### ISSUE TITLE
3.6.2: Unable to access jarfile bin/scala-cli.jar

### ISSUE THREAD

**Issue by francisdb** [scala/scala3#22196]
As with scala3 3.5.x and before I download https://github.com/scala/scala3/releases/download/3.6.2/scala3-3.6.2.tar.gz

However when I run the binary I get this:

`3.6.2`

```bash
./bin/scala --version
Error: Unable to access jarfile /cwd/bin/scala-cli.jar
```

`3.5.2`

```bash
./bin/scala --version
Scala code runner version: 1.4.3
Scala version (default): 3.5.2
```

MacOS and Linux

**Comment by Gedochao** [comment]
Already solved in:
- https://github.com/scala/scala3/pull/22185
Closing this.
