### ISSUE TITLE
I found a usage of=:=, but i can't understand

### ISSUE THREAD

**Issue by SnowballPitcher** [scala/scala3#22215]
```
/**
   * Transforms each vertex attribute in the graph using the map function.
   *
   * @note The new graph has the same structure.  As a consequence the underlying index structures
   * can be reused.
   *
   * @param map the function from a vertex object to a new vertex value
   *
   * @tparam VD2 the new vertex data type
   *
   * @example We might use this operation to change the vertex values
   * from one type to another to initialize an algorithm.
   * {{{
   * val rawGraph: Graph[(), ()] = Graph.textFile("hdfs://file")
   * val root = 42
   * var bfsGraph = rawGraph.mapVertices[Int]((vid, data) => if (vid == root) 0 else Math.MaxValue)
   * }}}
   *
   */
  def mapVertices[VD2: ClassTag](map: (VertexId, VD) => VD2)
    (implicit eq: VD =:= VD2 = null): Graph[VD2, ED]
```
    
    I'm new to Scala. The above code is from spark-graphx.
    
    My question is that now that the default value of eq is set to null, why still keep the code( (implicit eq: VD =:= VD2 = null))  .
    
    Does this mean there is some method to enable type check even when the default value of eq is null?

**Comment by soronpo** [comment]
Hi, welcome to Scala. 
User questions should be placed at https://users.scala-lang.org/ 
This is a specific `spark-graphx` question, so I suggest asking their maintainers.

**Comment by SnowballPitcher** [comment]
> Hi, welcome to Scala. User questions should be placed at https://users.scala-lang.org/ This is a specific `spark-graphx` question, so I suggest asking their maintainers.

ok, thank you for reminding me
