### ISSUE TITLE
Matches on union types do not infer most precise return type with wildcard matches

### ISSUE THREAD

**Issue by propensive** [scala/scala3#5420]
Considering a match on a union type, such as,
```
def unify(x: Int | String) = x match {
  case i: Int => "one"
  case other => other
}
```
the compiler will infer the return type as `Any`, being the LUB of `String` (from the first case clause) and `Int | String` (from the wildcard).

But it could calculate the precise return type, `String`, as it already knows the types being handled by the wildcard match, which it would report as failures for an exhaustivity warning. It could union these with the return types of each other case clause.

Note that if there is no wildcard match in the match block, the typechecker *will* correctly calculate the precise type. As intended by design, it will *infer* a LUB, but will still correctly typecheck the more precise union type.

I see a particularly strong potential use case for this in error handling, for example, this,
```
def aggregateErrs(data: Either[FileError | DiskError | ValidationError, String]) =
  data.left.map {
    case FileError => IoError()
    case DiskError => IoError()
    case other => other
  }
```
could infer the type `Either[IoError | ValidationError, String]`.

(The choice between automatically inferring a LUB or a union type, in the absence of an explicit ascription, is relevant in this example, but is not the issue I'm raising here. However in this example, my preference would be for the union type to be inferred.)

**Comment by smarter** [comment]
> But it could calculate the precise return type, String, as it already knows the types being handled by the wildcard match, which it would report as failures for an exhaustivity warning

This is true assuming that exhaustivity checking is perfect, which is what we strive for, but it's not clear that this is achievable in the presence of GADTs: https://github.com/lampepfl/dotty/issues/4029

Of course, exhaustivity checking is easier when the selector is a union type, but then we'd be introducing a special-case in the language where the semantics of a wildcard pattern depend on what you're pattern matching against. Personally, I don't think that's worth it.

> (The choice between automatically inferring a LUB or a union type, in the absence of an explicit ascription, is relevant in this example, but is not the issue I'm raising here. However in this example, my preference would be for the union type to be inferred.)

Yeah, we still haven't figured a good rule here, see the section "Type Inference" of http://dotty.epfl.ch/docs/reference/union-types-spec.html for a recap of the situation.

**Comment by propensive** [comment]
Thanks for the feedback, @smarter! I think there would be pretty big advantages to being able to treat union types as a direct type-level representation of a set, with support for removals. (And the last part is something that Scala 2 can't do.)

But I get the point about GADTs. As I understand it, though, the special casing would be the same special-casing that already applies to the exhaustivity warnings. There would always be the fallback of the current behavior.

Anyway, I'll try to find a moment to ask @odersky about it at SBTB this week.

**Comment by Blaisorblade** [comment]
> As I understand it, though, the special casing would be the same special-casing that already applies to the exhaustivity warnings. There would always be the fallback of the current behavior.

Not quite. The options are:
1. keep current behavior: `other` has the scrutinee's type. OK!
2. always compute the type of `other` through the exhaustivity checker: that risks unsoundness if the exhaustivity checker is incomplete. NOT OK!
3. have *a different set of* exhaustivity-checking-like rules to compute the type of `other`, that only work for union types but follow current rules for GADTs. CONFUSING?! (And IIUC that's @smarter's point).

OTOH, if you look at languages with union types where your example works, maybe option 3 seems more attractive, tho all the issues stand.

There is a fourth, but MUCH harder option to do in general (and pretty unlikely to happen): make subtype checking *detect* when we know it loses completeness. That could affect both exhaustivity warnings and typechecking in the same way. But it would both complicate typechecking (in a performance-critical method, of all places) and increase risks for soundness.

**Comment by LPTK** [comment]
[Here's](http://www.typescriptlang.org/play/#src=%0D%0Atype%20Doc%20%3D%20FeatureDoc%20%26%20Feature2Doc%0D%0Atype%20FeatureDoc%20%3D%0D%0A%20%20%7B%20has_feature%3A%20true%3B%20feature_settings%3A%20FeatureSetting%20%7D%20%7C%20%7B%20has_feature%3A%20false%20%7D%0D%0Atype%20Feature2Doc%20%3D%0D%0A%20%20%7B%20has_feature2%3A%20true%3B%20feature_settings2%3A%20FeatureSetting%20%7D%20%7C%20%7B%20has_feature2%3A%20false%20%7D%0D%0Atype%20FeatureSetting%20%3D%20%7B%20key%3A%20string%20%7D%0D%0A%0D%0Afunction%20test(d%3A%20Doc)%20%7B%0D%0A%20%20%20%20switch%20(d.has_feature)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20true%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(d.feature_settings.key)%0D%0A%20%20%20%20%20%20%20%20case%20false%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20console.log(d.feature_settings.key)%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20%5E%20type%20error%3A%20Property%20'feature_settings'%20does%20not%20exist%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Atest(%7B%20has_feature%3A%20true%2C%20feature_settings%3A%20%7B%20key%3A%20%22ok%22%20%7D%2C%20has_feature2%3A%20false%20%7D)%0D%0A%0D%0A%2F%2F%20test(%7B%20has_feature%3A%20true%2C%20feature_settings%3A%20%7B%20key%3A%20%22ok%22%20%7D%2C%20has_feature2%3A%20true%20%7D)%0D%0A%2F%2F%20%5E%20type%20error%3A%20Argument%20is%20not%20assignable%20to%20parameter%20of%20type%20'Doc'%0D%0A) what to strive for IMHO: the way TypeScript handles these things is really powerful but also really natural. It makes handling strongly-typed JSON data a breeze, as intersections and unions of structural types with literal types:

```typescript
type Doc = FeatureDoc & Feature2Doc
type FeatureDoc =
  { has_feature: true; feature_settings: FeatureSetting } | { has_feature: false }
type Feature2Doc =
  { has_feature2: true; feature_settings2: FeatureSetting } | { has_feature2: false }
type FeatureSetting = { key: string }

function test(d: Doc) {
    switch (d.has_feature) {
        case true:
            console.log(d.feature_settings.key)
        case false:
            // console.log(d.feature_settings.key)
            // ^ type error: Property 'feature_settings' does not exist on this type
    }
}

test({ has_feature: true, feature_settings: { key: "ok" }, has_feature2: false })

// test({ has_feature: true, feature_settings: { key: "ok" }, has_feature2: true })
// ^ type error: Argument is not assignable to parameter of type 'Doc'
```

**Comment by Blaisorblade** [comment]
@LPTK I remember you mentioned TypeScript (tho I wasn't sure of the details). Tho what this feature actually asks to support is closer to:

```
function test(d: Doc) {
    switch (d.has_feature) {
        case false:
            // console.log(d.feature_settings.key)
            // ^ type error: Property 'feature_settings' does not exist on this type
        case _:
            console.log(d.feature_settings.key)
    }
}
```

(and I can easily believe TypeScript could support this).

My answer to all this is:
> OTOH, if you look at languages with union types where your example works, maybe option 3 seems more attractive, tho all the issues stand.

In any case, I'm just analyzing tradeoffs, not making a call.

==

Also, we don't have the basic "dependent typing" you describe, and that surely belongs to a separate issue, or more likely a Pre-SIP on contributors. It seems potentially cool for JSON, but it also seems to overlap even more with enums and case classes, and it's not obviously easy to add to Dotty (it could be comparable to GADTs in complexity).

I wonder a bit if it's interesting for @OlivierBlanvillain and @gsps's explorations.

**Comment by AleksanderBG** [comment]
Something to take into consideration: assume, for the sake of the argument, that we _do_ special case the type of "trailing wildcard" when matching on an union. What happens if we match on a case class that has a union field? On a tuple that contains a union? On a tuple that contains multiple unions? It may be that special casing a typing rule when matching on a union will be confusing and inconsistent, and solving the general case without losing too much performance will be non-trivial.

Could this be better solved with a helper method instead? The best I can come up with on the spot is something like:
```scala
val union: Int | String | Float | Double = ???
union
  .extract[Int](i => "int")
  .extract[Float](f => "float") : Either[String | Double, String]
```
But there may be a better way to write this.
