### ISSUE TITLE
Typeclass derivation for ordering not working

### ISSUE THREAD

**Issue by DReigada** [scala/scala3#6658]
The typeclass derivation example for ordering (shown here: http://dotty.epfl.ch/docs/reference/contextual/derivation.html) is not compiling.

It seems that the `Ordering` companion object does not define the `derived` method.

```scala
scala> enum Tree[T] derives Eql, Ordering, Pickling {
     |   case Branch(left: Tree[T], right: Tree[T])
     |   case Leaf(elem: T)
     | }
1 |enum Tree[T] derives Eql, Ordering, Pickling {
  |                                    ^^^^^^^^
  |                                    Not found: type Pickling
1 |enum Tree[T] derives Eql, Ordering, Pickling {
  |                          ^
  |               value derived is not a member of object scala.math.Ordering
```

**Comment by OlivierBlanvillain** [comment]
In the documentation `Ordering` is just an example (Commonly used examples are...) and does not refer to `scala.math.Ordering`. With a user defined `Ordering` typeclass and the appropriate typeclass derivation infrastructure in its companion object this should work as intended!

**Comment by okouyad** [comment]
but that is a terrible thing to do. very misleading doc. it should be explained in advanced

**Comment by som-snytt** [comment]
I agree that the doc is subpar. I had to learn the impl recently for checkUnused. It's just a convention but the doc sounds like magic.
